using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DiagramExplorer
{
    public class SampleInfo
    {
        public string Name { get; set; }

        public string Info { get; set; }
        public Func<Color,Color, Control> Sample { get; set; }

        public string Controls { get; set; } = "";

        public List<SampleInfo> Childs { get; set; } = new List<SampleInfo>();

        static List<SampleInfo> samples;

        public static List<SampleInfo> Samples
        {
            get
            {
                if (samples == null)
                {
                    samples = new List<SampleInfo>()
                    {
                        new SampleInfo()
                        {
                            Name ="📁 Unbound",
                            Info = "The folder contains various samples with unbound diagram.",
                            Childs =
                            {
                                new SampleInfo()
                                {
                                    Name = "📈 FlexChart family",
                                    Info = "Shows diagram of FlexChart visualization components.\nThe nodes includes images which is generated by corresponding component.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateFlexChartFamily,
                                    Controls = "Direction,EdgeRouting,SketchMode"
                                },
                                new SampleInfo()
                                {
                                    Name = "🕐 Diagram Clock",
                                    Info = "Dynamic graph representing current time.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateTimeDiagram,
                                    Controls = "Direction,EdgeRouting,SketchMode"
                                },
                                new SampleInfo()
                                {
                                    Name = "⏩ Dynamic Graph",
                                    Info = "Dynamic diagram generation with adaptive layout.\nClick on the diagram to pause / start generation.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateDynamicDiagram,
                                    Controls = "Direction,EdgeRouting"
                                },
                            }
                        },
                        new SampleInfo()
                        {
                            Name ="📁 Data Binding",
                            Info = "The folder contains various samples with data bound diagrams.",
                            Childs =
                            {
                                new SampleInfo()
                                {
                                    Name ="👥 OrgChart",
                                    Info = "Organizational chart created with hierarchical data.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateOrgChart,
                                    Controls = "Direction,EdgeRouting,Palette"
                                },
                                new SampleInfo()
                                {
                                    Name ="🦁 Animals",
                                    Info = "Animal classification bound to flat data collection.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateAnimalsDiagram,
                                    Controls = "Direction,EdgeRouting,Palette"
                                },
                            }
                        },
                        new SampleInfo()
                        {
                            Name ="📁 Usage Scenarios",
                            Info = "The folder contains various use cases of graph-based visualization.",
                            Childs = 
                            {
                               new SampleInfo()
                               {
                                    Name ="📚 Literature",
                                    Info = "Shows literature genre tree. The diagram is loaded from Mermaid.js graph.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateLiteratureDiagram,
                                    Controls = "Direction,EdgeRouting"
                                },
                                new SampleInfo()
                                {
                                    Name ="🌳 Decision Tree",
                                    Info = "Shows sample decision tree diagram. The diagram is loaded from Mermaid.js graph.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateDecisionTreeDiagram,
                                    Controls = "Direction,EdgeRouting"
                                },
                                new SampleInfo()
                                {
                                    Name ="💻 Programming Languages",
                                    Info = "Shows relationship and history of programming languages. The diagram is loaded from Mermaid.js graph.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateProgrammingLanguagesDiagram,
                                    Controls = "Direction,EdgeRouting"
                                },
                                new SampleInfo()
                                {
                                    Name ="👪 Family Tree",
                                    Info = "Shows relations between main characters of Games of Thrones. The diagram is loaded from Mermaid.js graph.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateFamilyTreeDiagram,
                                    Controls = "Direction,EdgeRouting"
                                },
                            }
                        },
                        new SampleInfo()
                        {
                            Name ="📁 Features",
                            Info = "The folder contains samples demonstrating various diagram features.",
                            Childs =
                            {
                               new SampleInfo()
                               {
                                    Name ="👆 Hit Testing",
                                    Info = "Move mouse over nodes and edges to highlight.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateHitTestingDiagram,
                                    Controls = "Direction,EdgeRouting"
                               },
                               new SampleInfo()
                               {
                                    Name = "💬 Tooltips",
                                    Info = "You can specify node and edge tooltips when creating FlexDiagram.",
                                    Sample = DiagramExplorer.Samples.Samples.CreateTooltipsDiagram,
                                    Controls = "Direction,EdgeRouting"
                               },
                               new SampleInfo()
                               {
                                   Name = "☑️ Selection",
                                   Info = "FlexDiagram support node selection with customizable selection style. Click on the node to select.",
                                   Sample = DiagramExplorer.Samples.Samples.CreateSelectionDiagram,
                                   Controls = "Direction,EdgeRouting"
                               },
                            }
                        },
                    };
                }
                return samples;
            }
        }
    }
}
