namespace FilterSample
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn1 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn2 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn3 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn4 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn5 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn6 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn7 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn8 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn9 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn10 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn11 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn12 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn13 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn14 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.Task task1 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Resource resource1 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource2 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource3 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource4 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource5 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource6 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource7 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource8 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource9 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource10 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource11 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource12 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource13 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource14 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource15 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource16 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource17 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource18 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Task task2 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task3 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.ResourceRef resourceRef1 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task4 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor1 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Task task5 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor2 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef2 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task6 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor3 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef3 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef4 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task7 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor4 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Task task8 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor5 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Task task9 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.ResourceRef resourceRef5 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef6 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task10 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor6 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef7 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task11 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor7 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Task task12 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor8 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef8 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef9 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task13 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor9 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef10 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef11 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task14 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor10 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Predecessor predecessor11 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef12 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef13 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task15 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor12 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef14 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task16 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor13 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Task task17 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task18 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.ResourceRef resourceRef15 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task19 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor14 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef16 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef17 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task20 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.ResourceRef resourceRef18 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef19 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task21 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.ResourceRef resourceRef20 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task22 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor15 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Task task23 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor16 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef21 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef22 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task24 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor17 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef23 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef24 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task25 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor18 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Predecessor predecessor19 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Predecessor predecessor20 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Task task26 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task27 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task28 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task29 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task30 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task31 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task32 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task33 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task34 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task35 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task36 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task37 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task38 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task39 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task40 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task41 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task42 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task43 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task44 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task45 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task46 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task47 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task48 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task49 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task50 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task51 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task52 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task53 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task54 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task55 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task56 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task57 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task58 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task59 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task60 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task61 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task62 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task63 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task64 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task65 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task66 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task67 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task68 = new C1.Win.GanttView.Task();
            this.ganttView = new C1.Win.GanttView.C1GanttView();
            this.btnMissNaming = new System.Windows.Forms.Button();
            this.btnMissingResource = new System.Windows.Forms.Button();
            this.btnPerformWithin = new System.Windows.Forms.Button();
            this.btnHaveNotes = new System.Windows.Forms.Button();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btnTobyOrToni = new System.Windows.Forms.Button();
            this.btnCompletedByCarole = new System.Windows.Forms.Button();
            this.btnLateOn = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.ganttView)).BeginInit();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // ganttView
            // 
            this.ganttView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.ganttView.BackColor = System.Drawing.SystemColors.Window;
            taskPropertyColumn1.Caption = "Task Mode";
            taskPropertyColumn1.ID = 281642421;
            taskPropertyColumn1.Property = C1.Win.GanttView.TaskProperty.Mode;
            taskPropertyColumn1.Width = 71;
            taskPropertyColumn2.Caption = "Task Name";
            taskPropertyColumn2.ID = 389283492;
            taskPropertyColumn2.Property = C1.Win.GanttView.TaskProperty.Name;
            taskPropertyColumn2.Width = 167;
            taskPropertyColumn3.Caption = "Duration";
            taskPropertyColumn3.ID = 1193980067;
            taskPropertyColumn3.Property = C1.Win.GanttView.TaskProperty.Duration;
            taskPropertyColumn3.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            taskPropertyColumn3.Width = 55;
            taskPropertyColumn4.Caption = "Duration Units";
            taskPropertyColumn4.ID = 1834393658;
            taskPropertyColumn4.Property = C1.Win.GanttView.TaskProperty.DurationUnits;
            taskPropertyColumn5.Caption = "Start";
            taskPropertyColumn5.ID = 878770404;
            taskPropertyColumn5.Property = C1.Win.GanttView.TaskProperty.Start;
            taskPropertyColumn5.Visible = false;
            taskPropertyColumn6.Caption = "Finish";
            taskPropertyColumn6.ID = 1347224272;
            taskPropertyColumn6.Property = C1.Win.GanttView.TaskProperty.Finish;
            taskPropertyColumn6.Visible = false;
            taskPropertyColumn7.Caption = "% Complete";
            taskPropertyColumn7.ID = 1303371270;
            taskPropertyColumn7.Property = C1.Win.GanttView.TaskProperty.PercentComplete;
            taskPropertyColumn7.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            taskPropertyColumn7.Visible = false;
            taskPropertyColumn8.Caption = "Constraint Type";
            taskPropertyColumn8.ID = 1686029953;
            taskPropertyColumn8.Property = C1.Win.GanttView.TaskProperty.ConstraintType;
            taskPropertyColumn8.Visible = false;
            taskPropertyColumn9.Caption = "Constraint Date";
            taskPropertyColumn9.ID = 1178233289;
            taskPropertyColumn9.Property = C1.Win.GanttView.TaskProperty.ConstraintDate;
            taskPropertyColumn9.Visible = false;
            taskPropertyColumn10.Caption = "Predecessors";
            taskPropertyColumn10.ID = 1777126625;
            taskPropertyColumn10.Property = C1.Win.GanttView.TaskProperty.Predecessors;
            taskPropertyColumn11.Caption = "Deadline";
            taskPropertyColumn11.ID = 1481072281;
            taskPropertyColumn11.Property = C1.Win.GanttView.TaskProperty.Deadline;
            taskPropertyColumn11.Visible = false;
            taskPropertyColumn12.Caption = "Calendar";
            taskPropertyColumn12.ID = 1736156873;
            taskPropertyColumn12.Property = C1.Win.GanttView.TaskProperty.Calendar;
            taskPropertyColumn12.Visible = false;
            taskPropertyColumn13.Caption = "Resource Names";
            taskPropertyColumn13.ID = 2017304018;
            taskPropertyColumn13.Property = C1.Win.GanttView.TaskProperty.ResourceNames;
            taskPropertyColumn13.Visible = false;
            taskPropertyColumn14.Caption = "Notes";
            taskPropertyColumn14.ID = 1642844192;
            taskPropertyColumn14.Property = C1.Win.GanttView.TaskProperty.Notes;
            taskPropertyColumn14.Visible = false;
            this.ganttView.Columns.Add(taskPropertyColumn1);
            this.ganttView.Columns.Add(taskPropertyColumn2);
            this.ganttView.Columns.Add(taskPropertyColumn3);
            this.ganttView.Columns.Add(taskPropertyColumn4);
            this.ganttView.Columns.Add(taskPropertyColumn5);
            this.ganttView.Columns.Add(taskPropertyColumn6);
            this.ganttView.Columns.Add(taskPropertyColumn7);
            this.ganttView.Columns.Add(taskPropertyColumn8);
            this.ganttView.Columns.Add(taskPropertyColumn9);
            this.ganttView.Columns.Add(taskPropertyColumn10);
            this.ganttView.Columns.Add(taskPropertyColumn11);
            this.ganttView.Columns.Add(taskPropertyColumn12);
            this.ganttView.Columns.Add(taskPropertyColumn13);
            this.ganttView.Columns.Add(taskPropertyColumn14);
            this.ganttView.DefaultWorkingTimes.Interval_1.Empty = false;
            this.ganttView.DefaultWorkingTimes.Interval_1.From = new System.DateTime(1, 1, 1, 9, 0, 0, 0);
            this.ganttView.DefaultWorkingTimes.Interval_1.To = new System.DateTime(1, 1, 1, 13, 0, 0, 0);
            this.ganttView.DefaultWorkingTimes.Interval_2.Empty = false;
            this.ganttView.DefaultWorkingTimes.Interval_2.From = new System.DateTime(1, 1, 1, 14, 0, 0, 0);
            this.ganttView.DefaultWorkingTimes.Interval_2.To = new System.DateTime(1, 1, 1, 18, 0, 0, 0);
            this.ganttView.GridWidth = 338;
            this.ganttView.Location = new System.Drawing.Point(0, 0);
            this.ganttView.Name = "ganttView";
            task1.ID = 1513498650;
            task1.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task1.Name = "New Book Launch schedule";
            task1.PercentComplete = 0.2152058891189326D;
            this.ganttView.ProjectSummary = task1;
            resource1.Cost = new decimal(new int[] {
            2700,
            0,
            0,
            0});
            resource1.ID = 1310257871;
            resource1.Name = "Toby Nixon";
            resource2.Cost = new decimal(new int[] {
            880,
            0,
            0,
            0});
            resource2.ID = 403942649;
            resource2.Name = "Vikas Jain";
            resource3.ID = 900059987;
            resource3.Name = "Carole Poland";
            resource4.ID = 775286470;
            resource4.Name = "Copyeditors";
            resource4.ResourceType = C1.Win.GanttView.ResourceType.Material;
            resource5.ID = 967675533;
            resource5.Name = "Dan Jump";
            resource6.ID = 38886245;
            resource6.Name = "Hany Morcos";
            resource7.ID = 237469361;
            resource7.Name = "Jane Dow";
            resource8.ID = 443042401;
            resource8.Name = "John Evans";
            resource9.ID = 1698044936;
            resource9.Name = "Jun Cao";
            resource10.ID = 1476859390;
            resource10.Name = "Katie Jordan";
            resource11.ID = 603908635;
            resource11.Name = "Luis Sousa";
            resource12.ID = 697558225;
            resource12.Name = "Printing Service";
            resource12.ResourceType = C1.Win.GanttView.ResourceType.Material;
            resource13.ID = 539828441;
            resource13.Name = "Robin Wood";
            resource14.ID = 1310682358;
            resource14.Name = "Sharon Salavaria";
            resource15.ID = 372390668;
            resource15.Name = "Toni Poe";
            resource16.Cost = new decimal(new int[] {
            8000,
            0,
            0,
            0});
            resource16.ID = 1423358882;
            resource16.Name = "Travel";
            resource17.ID = 1164843623;
            resource17.Name = "Wiliam Flash";
            resource18.ID = 260690927;
            resource18.Name = "Zac Woodall";
            this.ganttView.Resources.Add(resource1);
            this.ganttView.Resources.Add(resource2);
            this.ganttView.Resources.Add(resource3);
            this.ganttView.Resources.Add(resource4);
            this.ganttView.Resources.Add(resource5);
            this.ganttView.Resources.Add(resource6);
            this.ganttView.Resources.Add(resource7);
            this.ganttView.Resources.Add(resource8);
            this.ganttView.Resources.Add(resource9);
            this.ganttView.Resources.Add(resource10);
            this.ganttView.Resources.Add(resource11);
            this.ganttView.Resources.Add(resource12);
            this.ganttView.Resources.Add(resource13);
            this.ganttView.Resources.Add(resource14);
            this.ganttView.Resources.Add(resource15);
            this.ganttView.Resources.Add(resource16);
            this.ganttView.Resources.Add(resource17);
            this.ganttView.Resources.Add(resource18);
            this.ganttView.Size = new System.Drawing.Size(821, 477);
            this.ganttView.StartDate = new System.DateTime(2014, 2, 25, 0, 0, 0, 0);
            this.ganttView.TabIndex = 0;
            task2.ID = 373743850;
            task2.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task2.Name = "Planning Phase";
            task2.OutlineParentID = 1513498650;
            task2.PercentComplete = 0.19047619047619047D;
            task3.Duration = 1D;
            task3.ID = 1940039857;
            task3.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task3.Name = "Assign launch team members";
            task3.OutlineParentID = 373743850;
            task3.PercentComplete = 1D;
            resourceRef1.Amount = 1D;
            resourceRef1.ResourceID = 900059987;
            task3.ResourceRefs.Add(resourceRef1);
            task4.Duration = 1D;
            task4.DurationUnits = C1.Win.GanttView.DurationUnits.Weeks;
            task4.ID = 1902404950;
            task4.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task4.OutlineParentID = 373743850;
            task4.PercentComplete = 0.6D;
            predecessor1.PredecessorTaskID = 1940039857;
            task4.Predecessors.Add(predecessor1);
            task5.Duration = 1D;
            task5.DurationUnits = C1.Win.GanttView.DurationUnits.Weeks;
            task5.ID = 152489629;
            task5.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task5.Name = "Schedule author interviews";
            task5.OutlineParentID = 373743850;
            predecessor2.PredecessorTaskID = 1940039857;
            task5.Predecessors.Add(predecessor2);
            resourceRef2.Amount = 1D;
            resourceRef2.ResourceID = 1698044936;
            task5.ResourceRefs.Add(resourceRef2);
            task6.Duration = 2D;
            task6.DurationUnits = C1.Win.GanttView.DurationUnits.Weeks;
            task6.ID = 2091011055;
            task6.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task6.Name = "Design and order marketing material";
            task6.OutlineParentID = 373743850;
            predecessor3.PredecessorTaskID = 1940039857;
            task6.Predecessors.Add(predecessor3);
            resourceRef3.Amount = 1D;
            resourceRef3.ResourceID = 1310257871;
            resourceRef4.Amount = 1D;
            resourceRef4.ResourceID = 260690927;
            task6.ResourceRefs.Add(resourceRef3);
            task6.ResourceRefs.Add(resourceRef4);
            task7.Duration = 0D;
            task7.ID = 1524170823;
            task7.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task7.Name = "Planning complete!";
            task7.OutlineParentID = 373743850;
            predecessor4.PredecessorTaskID = 2091011055;
            task7.Predecessors.Add(predecessor4);
            task8.ConstraintDate = new System.DateTime(2014, 3, 3, 0, 0, 0, 0);
            task8.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task8.ID = 2118603263;
            task8.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task8.OutlineParentID = 1513498650;
            task8.PercentComplete = 0.43478260869565216D;
            predecessor5.PredecessorTaskID = 373743850;
            task8.Predecessors.Add(predecessor5);
            task9.ConstraintDate = new System.DateTime(2014, 3, 12, 0, 0, 0, 0);
            task9.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task9.Duration = 1D;
            task9.ID = 1266698008;
            task9.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task9.Name = "Kickoff book launch meeting";
            task9.OutlineParentID = 2118603263;
            task9.PercentComplete = 1D;
            resourceRef5.Amount = 1D;
            resourceRef5.ResourceID = 1310682358;
            resourceRef6.Amount = 1D;
            resourceRef6.ResourceID = 1310257871;
            task9.ResourceRefs.Add(resourceRef5);
            task9.ResourceRefs.Add(resourceRef6);
            task10.Duration = 2D;
            task10.ID = 1743047809;
            task10.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task10.OutlineParentID = 2118603263;
            task10.PercentComplete = 0.5D;
            predecessor6.PredecessorTaskID = 1266698008;
            task10.Predecessors.Add(predecessor6);
            resourceRef7.Amount = 1D;
            resourceRef7.ResourceID = 900059987;
            task10.ResourceRefs.Add(resourceRef7);
            task11.Duration = 6D;
            task11.ID = 525875640;
            task11.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task11.Name = "Plan author\'s travel itinerary";
            task11.OutlineParentID = 2118603263;
            task11.PercentComplete = 1D;
            predecessor7.PredecessorTaskID = 1266698008;
            task11.Predecessors.Add(predecessor7);
            task12.Duration = 1D;
            task12.DurationUnits = C1.Win.GanttView.DurationUnits.Weeks;
            task12.ID = 132405539;
            task12.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task12.Name = "Channel Sales prep";
            task12.OutlineParentID = 2118603263;
            predecessor8.PredecessorTaskID = 1266698008;
            task12.Predecessors.Add(predecessor8);
            resourceRef8.Amount = 1D;
            resourceRef8.ResourceID = 260690927;
            resourceRef9.Amount = 1D;
            resourceRef9.ResourceID = 38886245;
            task12.ResourceRefs.Add(resourceRef8);
            task12.ResourceRefs.Add(resourceRef9);
            task13.Finish = new System.DateTime(2014, 3, 24, 9, 0, 0, 0);
            task13.ID = 1353658744;
            task13.Name = "Complete book launch form";
            task13.OutlineParentID = 2118603263;
            task13.PercentComplete = 1D;
            predecessor9.PredecessorTaskID = 132405539;
            task13.Predecessors.Add(predecessor9);
            resourceRef10.Amount = 1D;
            resourceRef10.ResourceID = 1310257871;
            resourceRef11.Amount = 1D;
            resourceRef11.ResourceID = 403942649;
            task13.ResourceRefs.Add(resourceRef10);
            task13.ResourceRefs.Add(resourceRef11);
            task13.Start = new System.DateTime(2014, 3, 20, 9, 0, 0, 0);
            task14.DurationUnits = C1.Win.GanttView.DurationUnits.Weeks;
            task14.Finish = new System.DateTime(2014, 3, 27, 9, 0, 0, 0);
            task14.ID = 1396929467;
            task14.Name = "Prepare book sales kit";
            task14.OutlineParentID = 2118603263;
            predecessor10.PredecessorTaskID = 1266698008;
            predecessor11.PredecessorTaskID = 132405539;
            task14.Predecessors.Add(predecessor10);
            task14.Predecessors.Add(predecessor11);
            resourceRef12.Amount = 1D;
            resourceRef12.ResourceID = 38886245;
            resourceRef13.Amount = 1D;
            resourceRef13.ResourceID = 260690927;
            task14.ResourceRefs.Add(resourceRef12);
            task14.ResourceRefs.Add(resourceRef13);
            task14.Start = new System.DateTime(2014, 3, 20, 9, 0, 0, 0);
            task15.Duration = 2D;
            task15.ID = 518118730;
            task15.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task15.Name = "Distribute internal marketing material";
            task15.OutlineParentID = 2118603263;
            predecessor12.PredecessorTaskID = 1396929467;
            task15.Predecessors.Add(predecessor12);
            resourceRef14.Amount = 1D;
            resourceRef14.ResourceID = 260690927;
            task15.ResourceRefs.Add(resourceRef14);
            task16.ID = 1794896915;
            task16.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task16.Name = "Public Launch Phase";
            task16.OutlineParentID = 1513498650;
            predecessor13.PredecessorTaskID = 2118603263;
            task16.Predecessors.Add(predecessor13);
            task17.ID = 1105961502;
            task17.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task17.Name = "Author travel and appearances";
            task17.OutlineParentID = 1794896915;
            task18.ConstraintDate = new System.DateTime(2014, 3, 31, 0, 0, 0, 0);
            task18.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task18.Duration = 1D;
            task18.ID = 119033255;
            task18.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task18.Name = "Author radio interview";
            task18.OutlineParentID = 1105961502;
            resourceRef15.Amount = 1D;
            resourceRef15.ResourceID = 372390668;
            task18.ResourceRefs.Add(resourceRef15);
            task19.Duration = 1D;
            task19.ID = 1383214640;
            task19.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task19.Name = "Author reading and signing at book fair";
            task19.OutlineParentID = 1105961502;
            predecessor14.PredecessorTaskID = 119033255;
            task19.Predecessors.Add(predecessor14);
            resourceRef16.Amount = 1D;
            resourceRef16.ResourceID = 372390668;
            resourceRef17.Amount = 1D;
            resourceRef17.ResourceID = 1423358882;
            task19.ResourceRefs.Add(resourceRef16);
            task19.ResourceRefs.Add(resourceRef17);
            task20.ConstraintDate = new System.DateTime(2014, 3, 31, 0, 0, 0, 0);
            task20.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task20.Duration = 2D;
            task20.ID = 2061905321;
            task20.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task20.Name = "Distribute advance copies";
            task20.Notes = "Get recipient list from publicist";
            task20.OutlineParentID = 1794896915;
            resourceRef18.Amount = 1D;
            resourceRef18.ResourceID = 1310257871;
            resourceRef19.Amount = 1D;
            resourceRef19.ResourceID = 403942649;
            task20.ResourceRefs.Add(resourceRef18);
            task20.ResourceRefs.Add(resourceRef19);
            task21.ConstraintDate = new System.DateTime(2014, 3, 31, 0, 0, 0, 0);
            task21.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task21.Duration = 2D;
            task21.ID = 225039161;
            task21.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task21.Name = "Distribute book sales kit";
            task21.OutlineParentID = 1794896915;
            resourceRef20.Amount = 1D;
            resourceRef20.ResourceID = 260690927;
            task21.ResourceRefs.Add(resourceRef20);
            task22.Duration = 7D;
            task22.ID = 334780400;
            task22.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task22.OutlineParentID = 1794896915;
            predecessor15.PredecessorTaskID = 225039161;
            task22.Predecessors.Add(predecessor15);
            task23.Duration = 1D;
            task23.DurationUnits = C1.Win.GanttView.DurationUnits.Weeks;
            task23.ID = 950931069;
            task23.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task23.Name = "Launch public Web portal for book";
            task23.OutlineParentID = 1794896915;
            predecessor16.PredecessorTaskID = 225039161;
            task23.Predecessors.Add(predecessor16);
            resourceRef21.Amount = 1D;
            resourceRef21.ResourceID = 1310257871;
            resourceRef22.Amount = 1D;
            resourceRef22.ResourceID = 403942649;
            task23.ResourceRefs.Add(resourceRef21);
            task23.ResourceRefs.Add(resourceRef22);
            task24.Duration = 1D;
            task24.DurationUnits = C1.Win.GanttView.DurationUnits.Weeks;
            task24.ID = 349527667;
            task24.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task24.Name = "Launch social media programs for book";
            task24.OutlineParentID = 1794896915;
            predecessor17.PredecessorTaskID = 950931069;
            task24.Predecessors.Add(predecessor17);
            resourceRef23.Amount = 1D;
            resourceRef23.ResourceID = 1310257871;
            resourceRef24.Amount = 1D;
            resourceRef24.ResourceID = 403942649;
            task24.ResourceRefs.Add(resourceRef23);
            task24.ResourceRefs.Add(resourceRef24);
            task25.Duration = 0D;
            task25.ID = 1952630353;
            task25.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task25.Name = "Launch complete!";
            task25.OutlineParentID = 1794896915;
            predecessor18.PredecessorTaskID = 334780400;
            predecessor19.PredecessorTaskID = 950931069;
            predecessor20.PredecessorTaskID = 349527667;
            task25.Predecessors.Add(predecessor18);
            task25.Predecessors.Add(predecessor19);
            task25.Predecessors.Add(predecessor20);
            task26.ID = 1907411200;
            task27.ID = 557040271;
            task28.ID = 1772783385;
            task29.ID = 2094903358;
            task30.ID = 626127770;
            task31.ID = 104461576;
            task32.ID = 890975461;
            task33.ID = 1476994843;
            task34.ID = 1242069060;
            task35.ID = 244233220;
            task36.ID = 1890605695;
            task37.ID = 159678678;
            task38.ID = 1710019457;
            task39.ID = 1786831974;
            task40.ID = 35990369;
            task41.ID = 758534052;
            task42.ID = 686492856;
            task43.ID = 1304030759;
            task44.ID = 1321288092;
            task45.ID = 1015939034;
            task46.ID = 216473481;
            task47.ID = 2037590830;
            task48.ID = 1061679727;
            task49.ID = 221841874;
            task50.ID = 1530697032;
            task51.ID = 1995786867;
            task52.ID = 1414865794;
            task53.ID = 647554806;
            task54.ID = 971243530;
            task55.ID = 1919783097;
            task56.ID = 968785459;
            task57.ID = 1515204094;
            task58.ID = 892227204;
            task59.ID = 1766942900;
            task60.ID = 1343996224;
            task61.ID = 516376503;
            task62.ID = 1693906001;
            task63.ID = 1566078940;
            task64.ID = 1276277181;
            task65.ID = 48028054;
            task66.ID = 1200035595;
            task67.ID = 47175981;
            task68.ID = 500978750;
            this.ganttView.Tasks.Add(task2);
            this.ganttView.Tasks.Add(task3);
            this.ganttView.Tasks.Add(task4);
            this.ganttView.Tasks.Add(task5);
            this.ganttView.Tasks.Add(task6);
            this.ganttView.Tasks.Add(task7);
            this.ganttView.Tasks.Add(task8);
            this.ganttView.Tasks.Add(task9);
            this.ganttView.Tasks.Add(task10);
            this.ganttView.Tasks.Add(task11);
            this.ganttView.Tasks.Add(task12);
            this.ganttView.Tasks.Add(task13);
            this.ganttView.Tasks.Add(task14);
            this.ganttView.Tasks.Add(task15);
            this.ganttView.Tasks.Add(task16);
            this.ganttView.Tasks.Add(task17);
            this.ganttView.Tasks.Add(task18);
            this.ganttView.Tasks.Add(task19);
            this.ganttView.Tasks.Add(task20);
            this.ganttView.Tasks.Add(task21);
            this.ganttView.Tasks.Add(task22);
            this.ganttView.Tasks.Add(task23);
            this.ganttView.Tasks.Add(task24);
            this.ganttView.Tasks.Add(task25);
            this.ganttView.Tasks.Add(task26);
            this.ganttView.Tasks.Add(task27);
            this.ganttView.Tasks.Add(task28);
            this.ganttView.Tasks.Add(task29);
            this.ganttView.Tasks.Add(task30);
            this.ganttView.Tasks.Add(task31);
            this.ganttView.Tasks.Add(task32);
            this.ganttView.Tasks.Add(task33);
            this.ganttView.Tasks.Add(task34);
            this.ganttView.Tasks.Add(task35);
            this.ganttView.Tasks.Add(task36);
            this.ganttView.Tasks.Add(task37);
            this.ganttView.Tasks.Add(task38);
            this.ganttView.Tasks.Add(task39);
            this.ganttView.Tasks.Add(task40);
            this.ganttView.Tasks.Add(task41);
            this.ganttView.Tasks.Add(task42);
            this.ganttView.Tasks.Add(task43);
            this.ganttView.Tasks.Add(task44);
            this.ganttView.Tasks.Add(task45);
            this.ganttView.Tasks.Add(task46);
            this.ganttView.Tasks.Add(task47);
            this.ganttView.Tasks.Add(task48);
            this.ganttView.Tasks.Add(task49);
            this.ganttView.Tasks.Add(task50);
            this.ganttView.Tasks.Add(task51);
            this.ganttView.Tasks.Add(task52);
            this.ganttView.Tasks.Add(task53);
            this.ganttView.Tasks.Add(task54);
            this.ganttView.Tasks.Add(task55);
            this.ganttView.Tasks.Add(task56);
            this.ganttView.Tasks.Add(task57);
            this.ganttView.Tasks.Add(task58);
            this.ganttView.Tasks.Add(task59);
            this.ganttView.Tasks.Add(task60);
            this.ganttView.Tasks.Add(task61);
            this.ganttView.Tasks.Add(task62);
            this.ganttView.Tasks.Add(task63);
            this.ganttView.Tasks.Add(task64);
            this.ganttView.Tasks.Add(task65);
            this.ganttView.Tasks.Add(task66);
            this.ganttView.Tasks.Add(task67);
            this.ganttView.Tasks.Add(task68);
            this.ganttView.Timescale.BottomTier.Align = C1.Win.GanttView.ScaleLabelAlignment.Center;
            this.ganttView.Timescale.BottomTier.Format = "w";
            this.ganttView.Timescale.BottomTier.Visible = true;
            this.ganttView.Timescale.MiddleTier.Format = "nnnn d";
            this.ganttView.Timescale.MiddleTier.Units = C1.Win.GanttView.TimescaleUnits.Weeks;
            this.ganttView.Timescale.MiddleTier.Visible = true;
            // 
            // btnMissNaming
            // 
            this.btnMissNaming.Location = new System.Drawing.Point(40, 22);
            this.btnMissNaming.Name = "btnMissNaming";
            this.btnMissNaming.Size = new System.Drawing.Size(178, 25);
            this.btnMissNaming.TabIndex = 1;
            this.btnMissNaming.Text = "Missing Name Tasks";
            this.btnMissNaming.UseVisualStyleBackColor = true;
            this.btnMissNaming.Click += new System.EventHandler(this.btnMissNaming_Click);
            // 
            // btnMissingResource
            // 
            this.btnMissingResource.Location = new System.Drawing.Point(40, 53);
            this.btnMissingResource.Name = "btnMissingResource";
            this.btnMissingResource.Size = new System.Drawing.Size(178, 25);
            this.btnMissingResource.TabIndex = 1;
            this.btnMissingResource.Text = "Missing Resource Tasks";
            this.btnMissingResource.UseVisualStyleBackColor = true;
            this.btnMissingResource.Click += new System.EventHandler(this.btnMissingResource_Click);
            // 
            // btnPerformWithin
            // 
            this.btnPerformWithin.Location = new System.Drawing.Point(40, 84);
            this.btnPerformWithin.Name = "btnPerformWithin";
            this.btnPerformWithin.Size = new System.Drawing.Size(178, 50);
            this.btnPerformWithin.TabIndex = 1;
            this.btnPerformWithin.Text = "Tasks Are Performed Within\nMar 16 - Apr 1";
            this.btnPerformWithin.UseVisualStyleBackColor = true;
            this.btnPerformWithin.Click += new System.EventHandler(this.btnPerformWithin_Click);
            // 
            // btnHaveNotes
            // 
            this.btnHaveNotes.Location = new System.Drawing.Point(40, 140);
            this.btnHaveNotes.Name = "btnHaveNotes";
            this.btnHaveNotes.Size = new System.Drawing.Size(178, 25);
            this.btnHaveNotes.TabIndex = 1;
            this.btnHaveNotes.Text = "Tasks Have Notes";
            this.btnHaveNotes.UseVisualStyleBackColor = true;
            this.btnHaveNotes.Click += new System.EventHandler(this.btnHaveNotes_Click);
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox1.Controls.Add(this.btnTobyOrToni);
            this.groupBox1.Controls.Add(this.btnPerformWithin);
            this.groupBox1.Controls.Add(this.btnCompletedByCarole);
            this.groupBox1.Controls.Add(this.btnLateOn);
            this.groupBox1.Controls.Add(this.btnHaveNotes);
            this.groupBox1.Controls.Add(this.btnMissingResource);
            this.groupBox1.Controls.Add(this.btnMissNaming);
            this.groupBox1.Location = new System.Drawing.Point(828, 14);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(233, 463);
            this.groupBox1.TabIndex = 2;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Filter";
            // 
            // btnTobyOrToni
            // 
            this.btnTobyOrToni.Location = new System.Drawing.Point(40, 233);
            this.btnTobyOrToni.Name = "btnTobyOrToni";
            this.btnTobyOrToni.Size = new System.Drawing.Size(178, 50);
            this.btnTobyOrToni.TabIndex = 2;
            this.btnTobyOrToni.Text = "Tasks Perform By Toby Or Toni";
            this.btnTobyOrToni.UseVisualStyleBackColor = true;
            this.btnTobyOrToni.Click += new System.EventHandler(this.btnTobyOrToni_Click);
            // 
            // btnCompletedByCarole
            // 
            this.btnCompletedByCarole.Location = new System.Drawing.Point(40, 202);
            this.btnCompletedByCarole.Name = "btnCompletedByCarole";
            this.btnCompletedByCarole.Size = new System.Drawing.Size(178, 25);
            this.btnCompletedByCarole.TabIndex = 1;
            this.btnCompletedByCarole.Text = "Completed Tasks By Carole";
            this.btnCompletedByCarole.UseVisualStyleBackColor = true;
            this.btnCompletedByCarole.Click += new System.EventHandler(this.btnCompletedByCarole_Click);
            // 
            // btnLateOn
            // 
            this.btnLateOn.Location = new System.Drawing.Point(40, 171);
            this.btnLateOn.Name = "btnLateOn";
            this.btnLateOn.Size = new System.Drawing.Size(178, 25);
            this.btnLateOn.TabIndex = 1;
            this.btnLateOn.Text = "Late Tasks On Mar 16";
            this.btnLateOn.UseVisualStyleBackColor = true;
            this.btnLateOn.Click += new System.EventHandler(this.btnLateOn_Click);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1060, 477);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.ganttView);
            this.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "Form1";
            this.Text = "Filter Sample";
            ((System.ComponentModel.ISupportInitialize)(this.ganttView)).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private C1.Win.GanttView.C1GanttView ganttView;
        private System.Windows.Forms.Button btnMissNaming;
        private System.Windows.Forms.Button btnMissingResource;
        private System.Windows.Forms.Button btnPerformWithin;
        private System.Windows.Forms.Button btnHaveNotes;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button btnLateOn;
        private System.Windows.Forms.Button btnCompletedByCarole;
        private System.Windows.Forms.Button btnTobyOrToni;
    }
}

