namespace CustomTaskInfoDialog
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));

            Icon = (System.Drawing.Icon)resources.GetObject("$this.Icon");
            C1.Win.GanttView.BarStyle barStyle1 = new C1.Win.GanttView.BarStyle();
            C1.Win.GanttView.BarStyle barStyle2 = new C1.Win.GanttView.BarStyle();
            C1.Win.GanttView.BarStyle barStyle3 = new C1.Win.GanttView.BarStyle();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn1 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn2 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn3 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn4 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn5 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn6 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn7 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn8 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn9 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn10 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn11 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn12 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn13 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn14 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.Task task1 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Resource resource1 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource2 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource3 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource4 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Task task2 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task3 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.ResourceRef resourceRef1 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task4 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.BarStyle barStyle4 = new C1.Win.GanttView.BarStyle();
            C1.Win.GanttView.BarStyle barStyle5 = new C1.Win.GanttView.BarStyle();
            C1.Win.GanttView.Predecessor predecessor1 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef2 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task5 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor2 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef3 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task6 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor3 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Task task7 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task8 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor4 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef4 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task9 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor5 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef5 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task10 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor6 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.Task task11 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task12 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task13 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task14 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task15 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task16 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task17 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task18 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task19 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task20 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task21 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task22 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task23 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task24 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task25 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task26 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task27 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task28 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task29 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task30 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task31 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task32 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task33 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task34 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task35 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task36 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task37 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task38 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task39 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task40 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task41 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task42 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task43 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task44 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task45 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task46 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task47 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task48 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task49 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task50 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task51 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task52 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task53 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task54 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task55 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task56 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task57 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task58 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task59 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task60 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task61 = new C1.Win.GanttView.Task();
            this.c1GanttView1 = new C1.Win.GanttView.C1GanttView();
            ((System.ComponentModel.ISupportInitialize)(this.c1GanttView1)).BeginInit();
            this.SuspendLayout();
            // 
            // c1GanttView1
            // 
            this.c1GanttView1.BackColor = System.Drawing.SystemColors.Window;
            barStyle1.BarColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(135)))), ((int)(((byte)(220)))));
            barStyle1.BarShape = C1.Win.GanttView.BarShape.ThickBar;
            barStyle1.BarType = C1.Win.GanttView.BarType.AutoTask;
            barStyle1.RightText1_ID = -13;
            barStyle1.TopText1_ID = 839049373;
            barStyle2.BarColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(200)))), ((int)(((byte)(209)))));
            barStyle2.BarShape = C1.Win.GanttView.BarShape.ThickBar;
            barStyle2.BarType = C1.Win.GanttView.BarType.ManualTask;
            barStyle2.EndShape = 22;
            barStyle2.RightText1_ID = -13;
            barStyle2.StartShape = 21;
            barStyle2.TopText1_ID = 839049373;
            barStyle3.BarShape = C1.Win.GanttView.BarShape.TopBar;
            barStyle3.BarType = C1.Win.GanttView.BarType.SummaryTask;
            barStyle3.EndShape = 2;
            barStyle3.StartShape = 2;
            barStyle3.TopText1_ID = 839049373;
            this.c1GanttView1.BarStyles.Add(barStyle1);
            this.c1GanttView1.BarStyles.Add(barStyle2);
            this.c1GanttView1.BarStyles.Add(barStyle3);
            taskPropertyColumn1.ID = 115863021;
            taskPropertyColumn1.Property = C1.Win.GanttView.TaskProperty.Mode;
            taskPropertyColumn2.ID = 839049373;
            taskPropertyColumn2.Property = C1.Win.GanttView.TaskProperty.Name;
            taskPropertyColumn3.ID = 1824679307;
            taskPropertyColumn3.Property = C1.Win.GanttView.TaskProperty.Duration;
            taskPropertyColumn3.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            taskPropertyColumn4.ID = 492555211;
            taskPropertyColumn4.Property = C1.Win.GanttView.TaskProperty.DurationUnits;
            taskPropertyColumn5.ID = 715159541;
            taskPropertyColumn5.Property = C1.Win.GanttView.TaskProperty.Start;
            taskPropertyColumn6.ID = 142543729;
            taskPropertyColumn6.Property = C1.Win.GanttView.TaskProperty.Finish;
            taskPropertyColumn7.ID = 189872326;
            taskPropertyColumn7.Property = C1.Win.GanttView.TaskProperty.PercentComplete;
            taskPropertyColumn7.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            taskPropertyColumn7.Visible = false;
            taskPropertyColumn8.ID = 950914077;
            taskPropertyColumn8.Property = C1.Win.GanttView.TaskProperty.ConstraintType;
            taskPropertyColumn8.Visible = false;
            taskPropertyColumn9.ID = 1053593084;
            taskPropertyColumn9.Property = C1.Win.GanttView.TaskProperty.ConstraintDate;
            taskPropertyColumn9.Visible = false;
            taskPropertyColumn10.ID = 350181539;
            taskPropertyColumn10.Property = C1.Win.GanttView.TaskProperty.Predecessors;
            taskPropertyColumn10.Visible = false;
            taskPropertyColumn11.ID = 294597990;
            taskPropertyColumn11.Property = C1.Win.GanttView.TaskProperty.Deadline;
            taskPropertyColumn11.Visible = false;
            taskPropertyColumn12.ID = 278348232;
            taskPropertyColumn12.Property = C1.Win.GanttView.TaskProperty.Calendar;
            taskPropertyColumn12.Visible = false;
            taskPropertyColumn13.ID = 366124261;
            taskPropertyColumn13.Property = C1.Win.GanttView.TaskProperty.ResourceNames;
            taskPropertyColumn13.Visible = false;
            taskPropertyColumn14.ID = 1783824597;
            taskPropertyColumn14.Property = C1.Win.GanttView.TaskProperty.Notes;
            taskPropertyColumn14.Visible = false;
            this.c1GanttView1.Columns.Add(taskPropertyColumn1);
            this.c1GanttView1.Columns.Add(taskPropertyColumn2);
            this.c1GanttView1.Columns.Add(taskPropertyColumn3);
            this.c1GanttView1.Columns.Add(taskPropertyColumn4);
            this.c1GanttView1.Columns.Add(taskPropertyColumn5);
            this.c1GanttView1.Columns.Add(taskPropertyColumn6);
            this.c1GanttView1.Columns.Add(taskPropertyColumn7);
            this.c1GanttView1.Columns.Add(taskPropertyColumn8);
            this.c1GanttView1.Columns.Add(taskPropertyColumn9);
            this.c1GanttView1.Columns.Add(taskPropertyColumn10);
            this.c1GanttView1.Columns.Add(taskPropertyColumn11);
            this.c1GanttView1.Columns.Add(taskPropertyColumn12);
            this.c1GanttView1.Columns.Add(taskPropertyColumn13);
            this.c1GanttView1.Columns.Add(taskPropertyColumn14);
            this.c1GanttView1.DefaultWorkingTimes.Interval_1.Empty = false;
            this.c1GanttView1.DefaultWorkingTimes.Interval_1.From = new System.DateTime(1, 1, 1, 9, 0, 0, 0);
            this.c1GanttView1.DefaultWorkingTimes.Interval_1.To = new System.DateTime(1, 1, 1, 13, 0, 0, 0);
            this.c1GanttView1.DefaultWorkingTimes.Interval_2.Empty = false;
            this.c1GanttView1.DefaultWorkingTimes.Interval_2.From = new System.DateTime(1, 1, 1, 14, 0, 0, 0);
            this.c1GanttView1.DefaultWorkingTimes.Interval_2.To = new System.DateTime(1, 1, 1, 18, 0, 0, 0);
            this.c1GanttView1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.c1GanttView1.GridWidth = 218;
            this.c1GanttView1.Location = new System.Drawing.Point(0, 0);
            this.c1GanttView1.Name = "c1GanttView1";
            task1.ID = 970674227;
            task1.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task1.Name = "Project Summary Task";
            task1.PercentComplete = 0.7083333375D;
            this.c1GanttView1.ProjectSummary = task1;
            resource1.ID = 1622083619;
            resource1.Name = "Scarlett";
            resource2.ID = 1374314959;
            resource2.Name = "Thomas";
            resource3.ID = 1653216189;
            resource3.Name = "Peter";
            resource4.ID = 1847509816;
            resource4.Name = "Hassan";
            this.c1GanttView1.Resources.Add(resource1);
            this.c1GanttView1.Resources.Add(resource2);
            this.c1GanttView1.Resources.Add(resource3);
            this.c1GanttView1.Resources.Add(resource4);
            this.c1GanttView1.Size = new System.Drawing.Size(656, 405);
            this.c1GanttView1.StartDate = new System.DateTime(2014, 4, 15, 0, 0, 0, 0);
            this.c1GanttView1.TabIndex = 0;
            task2.Finish = new System.DateTime(2014, 4, 8, 9, 0, 0, 0);
            task2.ID = 1187951112;
            task2.Name = "Sprint 1";
            task2.OutlineParentID = 970674227;
            task2.PercentComplete = 0.60000000999999992D;
            task2.Start = new System.DateTime(2014, 3, 25, 0, 0, 0, 0);
            task3.Finish = new System.DateTime(2014, 3, 29, 0, 0, 0, 0);
            task3.ID = 763953103;
            task3.Name = "Task 1.1";
            task3.OutlineParentID = 1187951112;
            task3.PercentComplete = 1D;
            resourceRef1.Amount = 1D;
            resourceRef1.ResourceID = 1622083619;
            task3.ResourceRefs.Add(resourceRef1);
            task3.Start = new System.DateTime(2014, 3, 25, 0, 0, 0, 0);
            barStyle4.BarColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(135)))), ((int)(((byte)(220)))));
            barStyle4.BarShape = C1.Win.GanttView.BarShape.ThickBar;
            barStyle4.BarType = C1.Win.GanttView.BarType.AutoTask;
            barStyle4.RightText1_ID = -13;
            barStyle4.TopText1_ID = 839049373;
            barStyle5.BarColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(200)))), ((int)(((byte)(209)))));
            barStyle5.BarShape = C1.Win.GanttView.BarShape.ThickBar;
            barStyle5.BarType = C1.Win.GanttView.BarType.ManualTask;
            barStyle5.EndShape = 22;
            barStyle5.RightText1_ID = -13;
            barStyle5.StartShape = 21;
            barStyle5.TopText1_ID = 839049373;
            task4.BarStyles.Add(barStyle4);
            task4.BarStyles.Add(barStyle5);
            task4.Finish = new System.DateTime(2014, 4, 3, 9, 0, 0, 0);
            task4.ID = 1511903109;
            task4.Name = "Task 1.2";
            task4.OutlineParentID = 1187951112;
            predecessor1.PredecessorTaskID = 763953103;
            task4.Predecessors.Add(predecessor1);
            resourceRef2.Amount = 1D;
            resourceRef2.ResourceID = 1653216189;
            task4.ResourceRefs.Add(resourceRef2);
            task4.Start = new System.DateTime(2014, 3, 29, 0, 0, 0, 0);
            task5.ConstraintDate = new System.DateTime(2014, 4, 3, 0, 0, 0, 0);
            task5.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task5.Duration = 3D;
            task5.ID = 1825346952;
            task5.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task5.Name = "Task 1.3";
            task5.OutlineParentID = 1187951112;
            task5.PercentComplete = 0.6666667D;
            predecessor2.PredecessorTaskID = 1511903109;
            task5.Predecessors.Add(predecessor2);
            resourceRef3.Amount = 1D;
            resourceRef3.ResourceID = 1847509816;
            task5.ResourceRefs.Add(resourceRef3);
            task6.Finish = new System.DateTime(2014, 4, 8, 9, 0, 0, 0);
            task6.ID = 1077139004;
            task6.Name = "Complete Sprint 1";
            task6.OutlineParentID = 1187951112;
            predecessor3.PredecessorTaskID = 1825346952;
            task6.Predecessors.Add(predecessor3);
            task6.Start = new System.DateTime(2014, 4, 8, 9, 0, 0, 0);
            task7.Finish = new System.DateTime(2014, 4, 28, 9, 0, 0, 0);
            task7.ID = 1961218391;
            task7.Name = "Sprint 2";
            task7.OutlineParentID = 970674227;
            task7.PercentComplete = 0.7857142857142857D;
            task7.Start = new System.DateTime(2014, 4, 8, 9, 0, 0, 0);
            task8.ConstraintDate = new System.DateTime(2014, 4, 8, 0, 0, 0, 0);
            task8.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task8.Duration = 6D;
            task8.ID = 1129365440;
            task8.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task8.Name = "Task 2.1";
            task8.OutlineParentID = 1961218391;
            task8.PercentComplete = 0.5D;
            predecessor4.PredecessorTaskID = 1077139004;
            task8.Predecessors.Add(predecessor4);
            resourceRef4.Amount = 1D;
            resourceRef4.ResourceID = 1374314959;
            task8.ResourceRefs.Add(resourceRef4);
            task9.Finish = new System.DateTime(2014, 4, 28, 9, 0, 0, 0);
            task9.ID = 675416228;
            task9.Name = "Task 2.2";
            task9.OutlineParentID = 1961218391;
            task9.PercentComplete = 1D;
            predecessor5.PredecessorTaskID = 1129365440;
            task9.Predecessors.Add(predecessor5);
            resourceRef5.Amount = 1D;
            resourceRef5.ResourceID = 1653216189;
            task9.ResourceRefs.Add(resourceRef5);
            task9.Start = new System.DateTime(2014, 4, 16, 9, 0, 0, 0);
            task10.Finish = new System.DateTime(2014, 4, 28, 9, 0, 0, 0);
            task10.ID = 63380755;
            task10.Name = "Complete Sprint 2";
            task10.OutlineParentID = 1961218391;
            predecessor6.PredecessorTaskID = 675416228;
            task10.Predecessors.Add(predecessor6);
            task10.Start = new System.DateTime(2014, 4, 28, 9, 0, 0, 0);
            task11.ID = 1041196519;
            task12.ID = 1065666771;
            task13.ID = 1869723603;
            task14.ID = 1139603790;
            task15.ID = 1560741278;
            task16.ID = 1425805567;
            task17.ID = 723544461;
            task18.ID = 1625024465;
            task19.ID = 1598943533;
            task20.ID = 838099651;
            task21.ID = 545824578;
            task22.ID = 1828106548;
            task23.ID = 1657702805;
            task24.ID = 1042539893;
            task25.ID = 984344103;
            task26.ID = 1966528540;
            task27.ID = 447284804;
            task28.ID = 1845355371;
            task29.ID = 290316068;
            task30.ID = 998220569;
            task31.ID = 1718309192;
            task32.ID = 326036979;
            task33.ID = 923123043;
            task34.ID = 1679851278;
            task35.ID = 188689714;
            task36.ID = 507148195;
            task37.ID = 1075624029;
            task38.ID = 428946472;
            task39.ID = 1346676234;
            task40.ID = 1232819273;
            task41.ID = 1201758702;
            task42.ID = 2105687059;
            task43.ID = 1026127421;
            task44.ID = 775375388;
            task45.ID = 487608693;
            task46.ID = 683612193;
            task47.ID = 795531031;
            task48.ID = 860459586;
            task49.ID = 1482982052;
            task50.ID = 1784935651;
            task51.ID = 706118151;
            task52.ID = 1637670175;
            task53.ID = 2111275435;
            task54.ID = 490816137;
            task55.ID = 165670924;
            task56.ID = 1290051327;
            task57.ID = 1677731955;
            task58.ID = 1868896858;
            task59.ID = 527559007;
            task60.ID = 2006302060;
            task61.ID = 629854201;
            this.c1GanttView1.Tasks.Add(task2);
            this.c1GanttView1.Tasks.Add(task3);
            this.c1GanttView1.Tasks.Add(task4);
            this.c1GanttView1.Tasks.Add(task5);
            this.c1GanttView1.Tasks.Add(task6);
            this.c1GanttView1.Tasks.Add(task7);
            this.c1GanttView1.Tasks.Add(task8);
            this.c1GanttView1.Tasks.Add(task9);
            this.c1GanttView1.Tasks.Add(task10);
            this.c1GanttView1.Tasks.Add(task11);
            this.c1GanttView1.Tasks.Add(task12);
            this.c1GanttView1.Tasks.Add(task13);
            this.c1GanttView1.Tasks.Add(task14);
            this.c1GanttView1.Tasks.Add(task15);
            this.c1GanttView1.Tasks.Add(task16);
            this.c1GanttView1.Tasks.Add(task17);
            this.c1GanttView1.Tasks.Add(task18);
            this.c1GanttView1.Tasks.Add(task19);
            this.c1GanttView1.Tasks.Add(task20);
            this.c1GanttView1.Tasks.Add(task21);
            this.c1GanttView1.Tasks.Add(task22);
            this.c1GanttView1.Tasks.Add(task23);
            this.c1GanttView1.Tasks.Add(task24);
            this.c1GanttView1.Tasks.Add(task25);
            this.c1GanttView1.Tasks.Add(task26);
            this.c1GanttView1.Tasks.Add(task27);
            this.c1GanttView1.Tasks.Add(task28);
            this.c1GanttView1.Tasks.Add(task29);
            this.c1GanttView1.Tasks.Add(task30);
            this.c1GanttView1.Tasks.Add(task31);
            this.c1GanttView1.Tasks.Add(task32);
            this.c1GanttView1.Tasks.Add(task33);
            this.c1GanttView1.Tasks.Add(task34);
            this.c1GanttView1.Tasks.Add(task35);
            this.c1GanttView1.Tasks.Add(task36);
            this.c1GanttView1.Tasks.Add(task37);
            this.c1GanttView1.Tasks.Add(task38);
            this.c1GanttView1.Tasks.Add(task39);
            this.c1GanttView1.Tasks.Add(task40);
            this.c1GanttView1.Tasks.Add(task41);
            this.c1GanttView1.Tasks.Add(task42);
            this.c1GanttView1.Tasks.Add(task43);
            this.c1GanttView1.Tasks.Add(task44);
            this.c1GanttView1.Tasks.Add(task45);
            this.c1GanttView1.Tasks.Add(task46);
            this.c1GanttView1.Tasks.Add(task47);
            this.c1GanttView1.Tasks.Add(task48);
            this.c1GanttView1.Tasks.Add(task49);
            this.c1GanttView1.Tasks.Add(task50);
            this.c1GanttView1.Tasks.Add(task51);
            this.c1GanttView1.Tasks.Add(task52);
            this.c1GanttView1.Tasks.Add(task53);
            this.c1GanttView1.Tasks.Add(task54);
            this.c1GanttView1.Tasks.Add(task55);
            this.c1GanttView1.Tasks.Add(task56);
            this.c1GanttView1.Tasks.Add(task57);
            this.c1GanttView1.Tasks.Add(task58);
            this.c1GanttView1.Tasks.Add(task59);
            this.c1GanttView1.Tasks.Add(task60);
            this.c1GanttView1.Tasks.Add(task61);
            this.c1GanttView1.Timescale.BottomTier.Align = C1.Win.GanttView.ScaleLabelAlignment.Center;
            this.c1GanttView1.Timescale.BottomTier.Format = "w";
            this.c1GanttView1.Timescale.BottomTier.Visible = true;
            this.c1GanttView1.Timescale.MiddleTier.Format = "nnnn d";
            this.c1GanttView1.Timescale.MiddleTier.Units = C1.Win.GanttView.TimescaleUnits.Weeks;
            this.c1GanttView1.Timescale.MiddleTier.Visible = true;
            this.c1GanttView1.ShowDialog += new C1.Win.GanttView.ShowDialogEventHandler(this.c1GanttView1_ShowDialog);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(656, 405);
            this.Controls.Add(this.c1GanttView1);
            this.Name = "Form1";
            this.Text = "Form1";
            ((System.ComponentModel.ISupportInitialize)(this.c1GanttView1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private C1.Win.GanttView.C1GanttView c1GanttView1;
    }
}

