using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.IO;
using System.Windows.Forms;
using System.Xml;

namespace FlexPivotExplorer.Samples
{
    using C1.FlexPivot;
    using C1.Win.FlexPivot;

    public partial class Overview : UserControl
    {
        Timer _timer;
        string dataPath = Path.Combine(System.Windows.Forms.Application.StartupPath, "Data");

        public Overview()
        {
            InitializeComponent();
            labelStatus.Font = new Font(labelStatus.Font, FontStyle.Bold);

            // initialize timer 
            _timer = new Timer();
            _timer.Tick += timer_Tick;
            _timer.Interval = 1000;

            // where DataEngine data is stored
            c1FlexPivotPage1.FlexPivotPanel.Workspace.Init(dataPath);
            c1FlexPivotPage1.FlexPivotChart.UseAxisScrollbar = true;

            // build menu with FlexPivot views
            foreach (XmlNode nd in LoadViews().SelectNodes("FlexPivotViews/C1FlexPivot"))
                comboBox1.Items.Add(nd.Attributes["id"].Value);

            // show update log
            c1FlexPivotPage1.PivotEngine.StartUpdating += FlexPivotEngine_StartUpdating;
            c1FlexPivotPage1.Updated += c1FlexPivotPage1_Updated;
        }

        private XmlDocument LoadViews()
        {
            // build menu with FlexPivot views
            XmlDocument views = new XmlDocument();
            var assembly = System.Reflection.Assembly.GetExecutingAssembly();
            var resourceName = "FlexPivotExplorer.Data.FlexPivotViews.xml";
            string res;

            using (Stream stream = assembly.GetManifestResourceStream(resourceName))
            using (StreamReader reader = new StreamReader(stream))
            {
                res = reader.ReadToEnd();
            }
            views.LoadXml(res);
            return views;
        }

        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);
            _timer.Enabled = true;
        }

        protected override void Dispose(bool disposing)
        {
            // remove data generated by the C1 DataEngine
            try
            {
                Directory.Delete(dataPath, true);
            }
            catch { }

            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        // generate data
        void timer_Tick(object sender, EventArgs e)
        {
            // disable timer
            _timer.Enabled = false;

            // generate additional rows
            Cursor = Cursors.WaitCursor;
            string tableName = GenerateRows(1000000);
            
            // connect to data
            c1FlexPivotPage1.FlexPivotPanel.ConnectDataEngine(tableName);

            // set default view
            comboBox1.SelectedIndex = 0; 
            Cursor = Cursors.Default;
        }

        // change predefined view
        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            c1FlexPivotPage1.PivotEngine.BeginUpdate();

            //set predefined view
            XmlDocument views = LoadViews(); 
            XmlNode nd = views.SelectSingleNode(string.Format("FlexPivotViews/C1FlexPivot[@id='{0}']", comboBox1.SelectedItem));
            c1FlexPivotPage1.FlexPivotPanel.ViewDefinition = nd.OuterXml;

            // set lookups
            FillLookup("Country", "LookupCountry");
            FillLookup("Product", "LookupProduct");
            FillLookup("Customer", "LookupCustomer");
            FillLookup("Employee", "LookupEmployee");
            FillLookup("Category", "LookupCategory");

            // update
            c1FlexPivotPage1.PivotEngine.EndUpdate();
        }

        // show status
        void FlexPivotEngine_StartUpdating(object sender, EventArgs e)
        {
            labelStatus.Text = "Analyzing....";
        }

        // hide status
        void c1FlexPivotPage1_Updated(object sender, EventArgs e)
        {
            labelStatus.Text = string.Empty;
        }

        // generate additional rows, to show that C1FlexPivot can handle large data sets
        private string GenerateRows(int count)
        {
            // get predefined source data
            DataTable table = DemoDataSource("Sales");

            // read data from first rows
            int max = table.Rows.Count;
            object[] rd = new object[max];
            for (int i = 0; i < max; i++)
                rd[i] = table.Rows[i].ItemArray;

            // add data to the end of the table
            for (int i = 0; i < count; i += max)
            {
                for (int k = 0; k < max && (k + i) < count; k++)
                {
                    DataRow r = table.NewRow();
                    r.ItemArray = (object[])rd[k];
                    table.Rows.Add(r);
                }
            }
            string tableName = Guid.NewGuid().ToString();
            C1.DataEngine.DbConnector.GetData(c1FlexPivotPage1.FlexPivotPanel.Workspace, table, tableName);
            return tableName;
        }

        // set field lookup
        void FillLookup(string fieldName, string lookupName)
        {
            var field = c1FlexPivotPage1.FlexPivotPanel.PivotEngine.Fields[fieldName];
            if (field.Lookup == null)
                field.Lookup = GetLookup(lookupName);
        }

        // create a dictionary from two columns data
        Dictionary<object, string> GetLookup(string name)
        {
            var dict = new Dictionary<object, string>();
            DataTableReader reader = DemoDataSource(name).CreateDataReader();
            while (reader.Read())
                dict.Add(reader.GetValue(0), reader.GetValue(1).ToString());
            reader.Close();
            return dict;
        }

        public DataTable DemoDataSource(string member)
        {
            string sql = "SELECT * FROM Products";
            DataTable dt = new DataTable();
            if (member.Equals("Sales"))
            {
                sql = "SELECT DISTINCT " +
                    "([Order Details].UnitPrice * Quantity) * (1 - [Order Details].Discount) AS [Sales], " +
                    "Orders_olap.OrderDate AS [OrderDate], " +
                    "Products.ProductID AS [Product], " +
                    "Customers_olap.CompanyID AS [Customer], " +
                    "Customers_olap.CountryID AS [Country], " +
                    "Employees.EmployeeID AS [Employee], " +
                    "Categories.CategoryID AS [Category] " +
                "FROM  " +
                    "(Companies INNER JOIN " +
                    "(Countries INNER JOIN  " +
                    "(Employees INNER JOIN " +
                    "(Customers_olap INNER JOIN " +
                    "(Orders_olap INNER JOIN " +
                    "([Order Details] INNER JOIN " +
                    "(Products INNER JOIN Categories " +
                    "ON Categories.CategoryID = Products.CategoryID) " +
                    "ON Products.ProductID = [Order Details].ProductID) " +
                    "ON Orders_olap.OrderID = [Order Details].OrderID) " +
                    "ON Customers_olap.CustomerID = Orders_olap.CustomerID) " +
                    "ON Employees.EmployeeID = Orders_olap.EmployeeID) " +
                    "ON Countries.CountryID = Customers_olap.CountryID) " +
                    "ON Companies.CompanyID = Customers_olap.CountryID);";
            }
            else if (member.Equals("LookupCategory"))
            {
                sql = "SELECT [CategoryID], [CategoryName] FROM Categories";
            }
            else if (member.Equals("LookupCountry"))
            {
                sql = "SELECT [CountryID], [CountryName] FROM [Countries]";
            }
            else if (member.Equals("LookupCustomer"))
            {
                sql = "SELECT [CompanyID], [CompanyName] FROM [Companies]";
            }
            else if (member.Equals("LookupEmployee"))
            {
                sql = "SELECT Employees.EmployeeID, [LastName] + ', ' + [FirstName] AS Name FROM Employees";
            }
            else if (member.Equals("LookupProduct"))
            {
                sql = "SELECT [ProductID],[ProductName] FROM Products";
            }

            var table = DataSource.GetRows(sql);
            return table;
        }
    }
}
