namespace TouchDemo
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Code generated by the Form Designer

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Icon = (System.Drawing.Icon)resources.GetObject("$this.Icon");
            System.Windows.Forms.TreeNode treeNode1 = new System.Windows.Forms.TreeNode("Basic (Zoom and Scroll)");
            System.Windows.Forms.TreeNode treeNode2 = new System.Windows.Forms.TreeNode("ControlBar");
            System.Windows.Forms.TreeNode treeNode3 = new System.Windows.Forms.TreeNode("Show Control");
            System.Windows.Forms.TreeNode treeNode4 = new System.Windows.Forms.TreeNode("Pan Window");
            System.Windows.Forms.TreeNode treeNode5 = new System.Windows.Forms.TreeNode("Zoom Policy");
            System.Windows.Forms.TreeNode treeNode6 = new System.Windows.Forms.TreeNode("Misc");
            System.Windows.Forms.TreeNode treeNode7 = new System.Windows.Forms.TreeNode("C1Zoom", new System.Windows.Forms.TreeNode[] {
            treeNode1,
            treeNode2,
            treeNode3,
            treeNode4,
            treeNode5,
            treeNode6});
            System.Windows.Forms.TreeNode treeNode8 = new System.Windows.Forms.TreeNode("Basic (Zoom and Scroll)");
            System.Windows.Forms.TreeNode treeNode9 = new System.Windows.Forms.TreeNode("C1ZoomPanel", new System.Windows.Forms.TreeNode[] {
            treeNode8});
            System.Windows.Forms.TreeNode treeNode10 = new System.Windows.Forms.TreeNode("Multiple window Business app example with the Component");
            System.Windows.Forms.TreeNode treeNode11 = new System.Windows.Forms.TreeNode("C1ApplicationZoom", new System.Windows.Forms.TreeNode[] {
            treeNode10});
            System.Windows.Forms.TreeNode treeNode12 = new System.Windows.Forms.TreeNode("C1Magnifier");
            System.Windows.Forms.TreeNode treeNode13 = new System.Windows.Forms.TreeNode("Compare PictureBox and C1MultiScaleImage");
            System.Windows.Forms.TreeNode treeNode14 = new System.Windows.Forms.TreeNode("C1MultiScaleImage", new System.Windows.Forms.TreeNode[] {
            treeNode13});
            System.Windows.Forms.TreeNode treeNode15 = new System.Windows.Forms.TreeNode("Touch Events List");
            System.Windows.Forms.TreeNode treeNode16 = new System.Windows.Forms.TreeNode("ContextualUI");
            System.Windows.Forms.TreeNode treeNode17 = new System.Windows.Forms.TreeNode("AutoRepeat");
            System.Windows.Forms.TreeNode treeNode18 = new System.Windows.Forms.TreeNode("ImageViewer");
            System.Windows.Forms.TreeNode treeNode19 = new System.Windows.Forms.TreeNode("Drawing Board for Pen");
            System.Windows.Forms.TreeNode treeNode20 = new System.Windows.Forms.TreeNode("C1TouchEventProvider", new System.Windows.Forms.TreeNode[] {
            treeNode15,
            treeNode16,
            treeNode17,
            treeNode18,
            treeNode19});
            this.splitContainer2 = new System.Windows.Forms.SplitContainer();
            this.panel2 = new System.Windows.Forms.Panel();
            this.pbC1Logo = new System.Windows.Forms.PictureBox();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.splitContainer3 = new System.Windows.Forms.SplitContainer();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.panel1 = new System.Windows.Forms.Panel();
            this.myTabControl1 = new TouchDemo.MyTabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.treemenu = new TouchDemo.MyTreeView();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.label1 = new System.Windows.Forms.Label();
            this.searchlist = new System.Windows.Forms.ListBox();
            this.searchtext = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.pictureBox4 = new System.Windows.Forms.PictureBox();
            this.pictureBox5 = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).BeginInit();
            this.splitContainer2.Panel1.SuspendLayout();
            this.splitContainer2.Panel2.SuspendLayout();
            this.splitContainer2.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbC1Logo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer3)).BeginInit();
            this.splitContainer3.Panel1.SuspendLayout();
            this.splitContainer3.Panel2.SuspendLayout();
            this.splitContainer3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.panel1.SuspendLayout();
            this.myTabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox5)).BeginInit();
            this.SuspendLayout();
            // 
            // splitContainer2
            // 
            this.splitContainer2.BackColor = System.Drawing.Color.Transparent;
            this.splitContainer2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer2.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.splitContainer2.IsSplitterFixed = true;
            this.splitContainer2.Location = new System.Drawing.Point(0, 0);
            this.splitContainer2.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.splitContainer2.Name = "splitContainer2";
            this.splitContainer2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer2.Panel1
            // 
            this.splitContainer2.Panel1.BackgroundImage = global::TouchDemo.Properties.Resources.header_b;
            this.splitContainer2.Panel1.Controls.Add(this.panel2);
            this.splitContainer2.Panel1.Controls.Add(this.pictureBox3);
            this.splitContainer2.Panel1.Controls.Add(this.pictureBox2);
            // 
            // splitContainer2.Panel2
            // 
            this.splitContainer2.Panel2.Controls.Add(this.splitContainer3);
            this.splitContainer2.Size = new System.Drawing.Size(1138, 776);
            this.splitContainer2.SplitterDistance = 136;
            this.splitContainer2.SplitterWidth = 6;
            this.splitContainer2.TabIndex = 0;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.White;
            this.panel2.Controls.Add(this.pbC1Logo);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(1138, 121);
            this.panel2.TabIndex = 12;
            // 
            // pbC1Logo
            // 
            this.pbC1Logo.BackColor = System.Drawing.Color.White;
            this.pbC1Logo.Image = ((System.Drawing.Image)(resources.GetObject("pbC1Logo.Image")));
            this.pbC1Logo.Location = new System.Drawing.Point(8, 8);
            this.pbC1Logo.Name = "pbC1Logo";
            this.pbC1Logo.Size = new System.Drawing.Size(380, 102);
            this.pbC1Logo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.pbC1Logo.TabIndex = 9;
            this.pbC1Logo.TabStop = false;
            // 
            // pictureBox3
            // 
            this.pictureBox3.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pictureBox3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(164)))), ((int)(((byte)(31)))), ((int)(((byte)(53)))));
            this.pictureBox3.Location = new System.Drawing.Point(261, 116);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(877, 22);
            this.pictureBox3.TabIndex = 11;
            this.pictureBox3.TabStop = false;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Location = new System.Drawing.Point(0, 117);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(260, 22);
            this.pictureBox2.TabIndex = 10;
            this.pictureBox2.TabStop = false;
            // 
            // splitContainer3
            // 
            this.splitContainer3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer3.IsSplitterFixed = true;
            this.splitContainer3.Location = new System.Drawing.Point(0, 0);
            this.splitContainer3.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.splitContainer3.Name = "splitContainer3";
            this.splitContainer3.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer3.Panel1
            // 
            this.splitContainer3.Panel1.Controls.Add(this.splitContainer1);
            this.splitContainer3.Panel1.Padding = new System.Windows.Forms.Padding(7, 0, 0, 0);
            // 
            // splitContainer3.Panel2
            // 
            this.splitContainer3.Panel2.BackColor = System.Drawing.Color.White;
            this.splitContainer3.Panel2.Controls.Add(this.label2);
            this.splitContainer3.Panel2.Controls.Add(this.pictureBox4);
            this.splitContainer3.Panel2.Controls.Add(this.pictureBox5);
            this.splitContainer3.Size = new System.Drawing.Size(1138, 634);
            this.splitContainer3.SplitterDistance = 555;
            this.splitContainer3.SplitterWidth = 6;
            this.splitContainer3.TabIndex = 0;
            // 
            // splitContainer1
            // 
            this.splitContainer1.BackColor = System.Drawing.Color.Transparent;
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.splitContainer1.IsSplitterFixed = true;
            this.splitContainer1.Location = new System.Drawing.Point(7, 0);
            this.splitContainer1.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.splitContainer1.Panel1.Controls.Add(this.panel1);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.BackColor = System.Drawing.Color.White;
            this.splitContainer1.Panel2.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.splitContainer1.Size = new System.Drawing.Size(1131, 555);
            this.splitContainer1.SplitterDistance = 253;
            this.splitContainer1.SplitterWidth = 1;
            this.splitContainer1.TabIndex = 0;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Gainsboro;
            this.panel1.Controls.Add(this.myTabControl1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Padding = new System.Windows.Forms.Padding(7, 7, 7, 5);
            this.panel1.Size = new System.Drawing.Size(253, 555);
            this.panel1.TabIndex = 0;
            // 
            // myTabControl1
            // 
            this.myTabControl1.Controls.Add(this.tabPage1);
            this.myTabControl1.Controls.Add(this.tabPage2);
            this.myTabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.myTabControl1.Location = new System.Drawing.Point(7, 7);
            this.myTabControl1.Name = "myTabControl1";
            this.myTabControl1.SelectedIndex = 0;
            this.myTabControl1.Size = new System.Drawing.Size(239, 543);
            this.myTabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.treemenu);
            this.tabPage1.Location = new System.Drawing.Point(4, 29);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(231, 510);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Features";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // treemenu
            // 
            this.treemenu.BackColor = System.Drawing.Color.White;
            this.treemenu.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.treemenu.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treemenu.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
            this.treemenu.ForeColor = System.Drawing.Color.Black;
            this.treemenu.HideSelection = false;
            this.treemenu.Indent = 15;
            this.treemenu.ItemHeight = 25;
            this.treemenu.Location = new System.Drawing.Point(3, 3);
            this.treemenu.Name = "treemenu";
            treeNode1.Name = "Node4";
            treeNode1.Tag = "C1Zoom";
            treeNode1.Text = "Basic (Zoom and Scroll)";
            treeNode2.Name = "Node7";
            treeNode2.Text = "ControlBar";
            treeNode3.Name = "Node8";
            treeNode3.Text = "Show Control";
            treeNode4.Name = "Node0";
            treeNode4.Text = "Pan Window";
            treeNode5.Name = "Node2";
            treeNode5.Text = "Zoom Policy";
            treeNode6.Name = "Node0";
            treeNode6.Text = "Misc";
            treeNode7.Name = "Node0";
            treeNode7.Text = "C1Zoom";
            treeNode8.Name = "Node3";
            treeNode8.Tag = "C1ZoomPanel";
            treeNode8.Text = "Basic (Zoom and Scroll)";
            treeNode9.Name = "Node1";
            treeNode9.Text = "C1ZoomPanel";
            treeNode10.Name = "Node4";
            treeNode10.Text = "Multiple window Business app example with the Component";
            treeNode11.Name = "Node2";
            treeNode11.Text = "C1ApplicationZoom";
            treeNode12.Name = "Node1";
            treeNode12.Text = "C1Magnifier";
            treeNode13.Name = "Node0";
            treeNode13.Text = "Compare PictureBox and C1MultiScaleImage";
            treeNode14.Name = "Node2";
            treeNode14.Text = "C1MultiScaleImage";
            treeNode15.Name = "Node9";
            treeNode15.Text = "Touch Events List";
            treeNode16.Name = "Node10";
            treeNode16.Text = "ContextualUI";
            treeNode17.Name = "Node12";
            treeNode17.Text = "AutoRepeat";
            treeNode18.Name = "Node11";
            treeNode18.Text = "ImageViewer";
            treeNode19.Name = "Node2";
            treeNode19.Text = "Drawing Board for Pen";
            treeNode20.Name = "Node3";
            treeNode20.Text = "C1TouchEventProvider";
            this.treemenu.Nodes.AddRange(new System.Windows.Forms.TreeNode[] {
            treeNode7,
            treeNode9,
            treeNode11,
            treeNode12,
            treeNode14,
            treeNode20});
            this.treemenu.Size = new System.Drawing.Size(225, 504);
            this.treemenu.TabIndex = 1;
            this.treemenu.VisibleChanged += new System.EventHandler(this.treemenu_VisibleChanged);
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.Color.White;
            this.tabPage2.Controls.Add(this.label1);
            this.tabPage2.Controls.Add(this.searchlist);
            this.tabPage2.Controls.Add(this.searchtext);
            this.tabPage2.Location = new System.Drawing.Point(4, 29);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(231, 510);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Indexes";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(6, 10);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(64, 20);
            this.label1.TabIndex = 6;
            this.label1.Text = "Search:";
            // 
            // searchlist
            // 
            this.searchlist.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.searchlist.BackColor = System.Drawing.Color.White;
            this.searchlist.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.searchlist.ForeColor = System.Drawing.Color.Black;
            this.searchlist.FormattingEnabled = true;
            this.searchlist.ItemHeight = 20;
            this.searchlist.Location = new System.Drawing.Point(9, 38);
            this.searchlist.Name = "searchlist";
            this.searchlist.Size = new System.Drawing.Size(216, 240);
            this.searchlist.TabIndex = 5;
            // 
            // searchtext
            // 
            this.searchtext.Location = new System.Drawing.Point(79, 7);
            this.searchtext.Name = "searchtext";
            this.searchtext.Size = new System.Drawing.Size(146, 26);
            this.searchtext.TabIndex = 4;
            // 
            // label2
            // 
            this.label2.Font = new System.Drawing.Font("Segoe UI Light", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
            this.label2.Location = new System.Drawing.Point(3, 40);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(400, 15);
            this.label2.TabIndex = 14;
            // 
            // pictureBox4
            // 
            this.pictureBox4.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pictureBox4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(164)))), ((int)(((byte)(31)))), ((int)(((byte)(53)))));
            this.pictureBox4.Location = new System.Drawing.Point(260, 0);
            this.pictureBox4.Name = "pictureBox4";
            this.pictureBox4.Size = new System.Drawing.Size(877, 24);
            this.pictureBox4.TabIndex = 13;
            this.pictureBox4.TabStop = false;
            // 
            // pictureBox5
            // 
            this.pictureBox5.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox5.BackgroundImage = global::TouchDemo.Properties.Resources.header_b;
            this.pictureBox5.Location = new System.Drawing.Point(0, 0);
            this.pictureBox5.Name = "pictureBox5";
            this.pictureBox5.Size = new System.Drawing.Size(260, 24);
            this.pictureBox5.TabIndex = 12;
            this.pictureBox5.TabStop = false;
            // 
            // MainForm
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.ClientSize = new System.Drawing.Size(1138, 776);
            this.Controls.Add(this.splitContainer2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.MaximizeBox = false;
            this.MinimumSize = new System.Drawing.Size(1024, 729);
            this.Name = "MainForm";
            this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "C1TouchToolKit For WinForms Demo";
            this.splitContainer2.Panel1.ResumeLayout(false);
            this.splitContainer2.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).EndInit();
            this.splitContainer2.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbC1Logo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.splitContainer3.Panel1.ResumeLayout(false);
            this.splitContainer3.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer3)).EndInit();
            this.splitContainer3.ResumeLayout(false);
            this.splitContainer1.Panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.myTabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox5)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.SplitContainer splitContainer2;
        private System.Windows.Forms.SplitContainer splitContainer3;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.PictureBox pbC1Logo;
        private MyTabControl myTabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private MyTreeView treemenu;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ListBox searchlist;
        private System.Windows.Forms.TextBox searchtext;
        private System.Windows.Forms.PictureBox pictureBox3;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.PictureBox pictureBox4;
        private System.Windows.Forms.PictureBox pictureBox5;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Panel panel2;
    }
}

