//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloatingBarChart.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FloatingBarChart.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb_down {
            get {
                object obj = ResourceManager.GetObject("cb_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb_down26 {
            get {
                object obj = ResourceManager.GetObject("cb_down26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb_up {
            get {
                object obj = ResourceManager.GetObject("cb_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb_up26 {
            get {
                object obj = ResourceManager.GetObject("cb_up26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;samples&gt;
        ///  &lt;sample id=&quot;lines&quot;&gt;
        ///    &lt;title&gt;Line Styles&lt;/title&gt;
        ///    &lt;description&gt;
        ///      The sample below shows how to customize a single line series with different styles and colors.
        ///    &lt;/description&gt;
        ///  &lt;/sample&gt;
        ///  &lt;sample id=&quot;legenditems&quot;&gt;
        ///    &lt;title&gt;Legend Items&lt;/title&gt;
        ///    &lt;description&gt;The sample below shows each point of a series in a different color and displays its corresponding entry in the Legend.&lt;/description&gt;
        ///  &lt;/sample&gt;
        ///  &lt;sample id=&quot;legendrange [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExplorerConfiguration_CH {
            get {
                return ResourceManager.GetString("ExplorerConfiguration_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;samples&gt;
        ///  &lt;sample id=&quot;lines&quot;&gt;
        ///    &lt;title&gt;Line Styles&lt;/title&gt;
        ///    &lt;description&gt;
        ///      The sample below shows how to customize a single line series with different styles and colors.
        ///    &lt;/description&gt;
        ///  &lt;/sample&gt;
        ///  &lt;sample id=&quot;legenditems&quot;&gt;
        ///    &lt;title&gt;Legend Items&lt;/title&gt;
        ///    &lt;description&gt;The sample below shows each point of a series in a different color and displays its corresponding entry in the Legend.&lt;/description&gt;
        ///  &lt;/sample&gt;
        ///  &lt;sample id=&quot;legendrange [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExplorerConfiguration_EN {
            get {
                return ResourceManager.GetString("ExplorerConfiguration_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;samples&gt;
        ///  &lt;sample id=&quot;lines&quot;&gt;
        ///    &lt;title&gt;Line Styles&lt;/title&gt;
        ///    &lt;description&gt;
        ///      The sample below shows how to customize a single line series with different styles and colors.
        ///    &lt;/description&gt;
        ///  &lt;/sample&gt;
        ///  &lt;sample id=&quot;legenditems&quot;&gt;
        ///    &lt;title&gt;Legend Items&lt;/title&gt;
        ///    &lt;description&gt;The sample below shows each point of a series in a different color and displays its corresponding entry in the Legend.&lt;/description&gt;
        ///  &lt;/sample&gt;
        ///  &lt;sample id=&quot;legendrange [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExplorerConfiguration_JP {
            get {
                return ResourceManager.GetString("ExplorerConfiguration_JP", resourceCulture);
            }
        }
    }
}
