//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tooltips.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tooltips.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month: {Name}
        ///S: {Sales}
        ///E: {Expenses}.
        /// </summary>
        internal static string FlexChartRegularTooltipContent {
            get {
                return ResourceManager.GetString("FlexChartRegularTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit:{Fruit}
        ///Value:{Value}.
        /// </summary>
        internal static string FlexPieRegularTooltipContent {
            get {
                return ResourceManager.GetString("FlexPieRegularTooltipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oranges, Apples,Pears,Bananas.
        /// </summary>
        internal static string FruitsList {
            get {
                return ResourceManager.GetString("FruitsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan,Feb,March,April,May,June,July,August,Sept,Oct,Nov,Dec.
        /// </summary>
        internal static string MonthNames {
            get {
                return ResourceManager.GetString("MonthNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly Values - .
        /// </summary>
        internal static string OrderChartFooter {
            get {
                return ResourceManager.GetString("OrderChartFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart as Tooltips.
        /// </summary>
        internal static string TitleChartTooltips {
            get {
                return ResourceManager.GetString("TitleChartTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Tooltips.
        /// </summary>
        internal static string TitleHTMLTooltips {
            get {
                return ResourceManager.GetString("TitleHTMLTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Tooltips.
        /// </summary>
        internal static string TitleRegularTooltips {
            get {
                return ResourceManager.GetString("TitleRegularTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Tooltip.
        /// </summary>
        internal static string ToolStripItemChartTooltip {
            get {
                return ResourceManager.GetString("ToolStripItemChartTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ToolStripItemView {
            get {
                return ResourceManager.GetString("ToolStripItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Tooltip.
        /// </summary>
        internal static string TooltStripItemHTMLTooltip {
            get {
                return ResourceManager.GetString("TooltStripItemHTMLTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Tooltip.
        /// </summary>
        internal static string TooltStripItemRegularTooltip {
            get {
                return ResourceManager.GetString("TooltStripItemRegularTooltip", resourceCulture);
            }
        }
    }
}
