'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ErrorProvider.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter values that add up to at least &lt;b&gt;100&lt;/b&gt;..
        '''</summary>
        Friend ReadOnly Property Err100() As String
            Get
                Return ResourceManager.GetString("Err100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a time &lt;b&gt;after&lt;/b&gt; 12:00.&lt;br&gt;Anything earlier than that is uncivilized....
        '''</summary>
        Friend ReadOnly Property ErrAfter12() As String
            Get
                Return ResourceManager.GetString("ErrAfter12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter an &lt;b&gt;even&lt;/b&gt; number.&lt;br&gt;
        '''&lt;i&gt;In case you have forgotten (nothing to be
        '''ashamed of ;-), even numbers are&lt;br&gt;
        '''&lt;b&gt;integers&lt;/b&gt; divisible by 2 with no
        '''remainder (e.g. 0, 2, 4, 6, etc.)&lt;/i&gt;.
        '''</summary>
        Friend ReadOnly Property ErrEven() As String
            Get
                Return ResourceManager.GetString("ErrEven", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please check at least one of the checkboxes,&lt;br&gt; otherwise I won&apos;t know what to do....
        '''</summary>
        Friend ReadOnly Property ErrOneBox() As String
            Get
                Return ResourceManager.GetString("ErrOneBox", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ErrorInfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ErrorInfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a value that starts with &lt;b&gt;&apos;a&apos;&lt;/b&gt; (lowercase).&lt;br&gt;
        '''&lt;i&gt;Other values are not accepted because they
        '''will compromise our sorting algorithm.
        '''&lt;br&gt;We will get this fixed eventually, but
        '''for now please oblige... &lt;b&gt;Thank you!&lt;/b&gt;&lt;/i&gt;..
        '''</summary>
        Friend ReadOnly Property ErrStartWithA() As String
            Get
                Return ResourceManager.GetString("ErrStartWithA", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
