'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4016
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>" & ControlChars.CrLf & "<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">" & ControlChars.CrLf & "  <string>Hanari Carnes</string>" & ControlChars.CrLf & "  <string>Hungry Coyote Import Store</string>" & ControlChars.CrLf & "  <string>Island Trading</string>" & ControlChars.CrLf & "  <string>Laughing Bacchus Wine Cellars</string>" & ControlChars.CrLf & "  <string>Rancho grande</string>" & ControlChars.CrLf & "  <string>La maison d'Asie</string>" & ControlChars.CrLf & "  <string>La corne d'abondance</string>" & ControlChars.CrLf & "</ArrayOfString>")> _
		Public Property Customers() As Global.System.Collections.Specialized.StringCollection
			Get
				Return (CType(Me("Customers"), Global.System.Collections.Specialized.StringCollection))
			End Get
			Set(ByVal value As System.Collections.Specialized.StringCollection)
				Me("Customers") = value
			End Set
		End Property
	End Class
End Namespace
