//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlExplorer.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Editor
        {
            get
            {
                object obj = ResourceManager.GetObject("Icon_Editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_FlexGrid
        {
            get
            {
                object obj = ResourceManager.GetObject("Icon_FlexGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_MultiColumnCombo
        {
            get
            {
                object obj = ResourceManager.GetObject("Icon_MultiColumnCombo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_MultiSelect
        {
            get
            {
                object obj = ResourceManager.GetObject("Icon_MultiSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_DataFilter
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_DataFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_FlexGrid
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_FlexGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_FlexChart
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_FlexChart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_FlexPie
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_FlexPie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_TreeMap
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_TreeMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Guage
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Guage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Map
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Editor
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_MultiColCom
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_MultiColCom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_MulSelect
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_MulSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Accordion
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Accordion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_DocTab
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_DocTab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Ribbon
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Ribbon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_ToolboxSizer
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_ToolboxSizer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_SuperTooltip
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_SuperTooltip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_TileControl
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_TileControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Toolbars
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Toolbars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_TreeView
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_TreeView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_GranttView
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_GranttView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Scheduler
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Scheduler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_FlexReport
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_FlexReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Flexiewer
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Flexiewer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Printing
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Printing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Barcode
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Barcode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_Bitmap
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Bitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_C1
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_C1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Ico_Expression
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Expression", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Ico_SpellChecker
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_SpellChecker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Ico_Themes
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_Themes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_TouchToolkit
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_TouchToolkit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_MultiSelect
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_MultiSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        internal static System.Drawing.Bitmap Ico_MultiSelectCombo
        {
            get
            {
                object obj = ResourceManager.GetObject("Ico_MultiSelectCombo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

    }
}
