//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrollBarAnnotations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrollBarAnnotations.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to enable or disable this feature..
        /// </summary>
        internal static string CheckToolTipMessage {
            get {
                return ResourceManager.GetString("CheckToolTipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show annotations marking products that are being discontinued, helping users quickly identify them in the grid..
        /// </summary>
        internal static string CustomAnnotationDescription {
            get {
                return ResourceManager.GetString("CustomAnnotationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Annotation for discontinued products.
        /// </summary>
        internal static string CustomAnnotations {
            get {
                return ResourceManager.GetString("CustomAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Options.
        /// </summary>
        internal static string DisplayOptions {
            get {
                return ResourceManager.GetString("DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Info.
        /// </summary>
        internal static string FeatureInfo {
            get {
                return ResourceManager.GetString("FeatureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys for navigation.
        /// </summary>
        internal static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable keyboard shortcuts for quicker navigation between annotated rows, including Ctrl+Down and Ctrl+Up to move between rows..
        /// </summary>
        internal static string HotKeysDescription {
            get {
                return ResourceManager.GetString("HotKeysDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product is discontinued.
        /// </summary>
        internal static string ProductDiscontinued {
            get {
                return ResourceManager.GetString("ProductDiscontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid Scrollbar Annotations.
        /// </summary>
        internal static string ScrollbarAnnotations {
            get {
                return ResourceManager.GetString("ScrollbarAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlexGrid Scrollbar Annotation feature enhances data visualization by adding contextual markers directly onto the grid’s scrollbar..
        /// </summary>
        internal static string ScrollbarAnnotationsDescription {
            get {
                return ResourceManager.GetString("ScrollbarAnnotationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid Scrollbar Annotations.
        /// </summary>
        internal static string ScrollbarAnnotationsTitle {
            get {
                return ResourceManager.GetString("ScrollbarAnnotationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Annotations.
        /// </summary>
        internal static string ShowAnnotations {
            get {
                return ResourceManager.GetString("ShowAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master switch for annotations. When disabled, all annotation markers and notes are hidden even if other annotation options are enabled..
        /// </summary>
        internal static string ShowAnnotationsDescription {
            get {
                return ResourceManager.GetString("ShowAnnotationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Errors.
        /// </summary>
        internal static string ShowErrors {
            get {
                return ResourceManager.GetString("ShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show error indicators directly in the interface to quickly spot issues..
        /// </summary>
        internal static string ShowErrorsDescription {
            get {
                return ResourceManager.GetString("ShowErrorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Focused Row.
        /// </summary>
        internal static string ShowFocusedRow {
            get {
                return ResourceManager.GetString("ShowFocusedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emphasize the row that currently has focus for better navigation..
        /// </summary>
        internal static string ShowFocusedRowDescription {
            get {
                return ResourceManager.GetString("ShowFocusedRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visually mark rows based on certain criteria to easily identify them. In this sample it will highlight letter &apos;S&apos;..
        /// </summary>
        internal static string ShowHighlightedRowDescription {
            get {
                return ResourceManager.GetString("ShowHighlightedRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Highlighted Rows (highlight letter &apos;S&apos;).
        /// </summary>
        internal static string ShowHighlightedRows {
            get {
                return ResourceManager.GetString("ShowHighlightedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a tooltip on the scrollbar that indicates your current row position as you scroll through the grid..
        /// </summary>
        internal static string ShowScrollTipDescription {
            get {
                return ResourceManager.GetString("ShowScrollTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Scroll ToolTip.
        /// </summary>
        internal static string ShowScrollToolTip {
            get {
                return ResourceManager.GetString("ShowScrollToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the currently selected row(s) to make it easier to track your focus..
        /// </summary>
        internal static string ShowSelectedRowDescription {
            get {
                return ResourceManager.GetString("ShowSelectedRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Selected Rows.
        /// </summary>
        internal static string ShowSelectedRows {
            get {
                return ResourceManager.GetString("ShowSelectedRows", resourceCulture);
            }
        }
    }
}
