namespace CustomColumn
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            C1.Win.GanttView.BarStyle barStyle1 = new C1.Win.GanttView.BarStyle();
            C1.Win.GanttView.BarStyle barStyle2 = new C1.Win.GanttView.BarStyle();
            C1.Win.GanttView.BarStyle barStyle3 = new C1.Win.GanttView.BarStyle();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn1 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn2 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.CustomFieldColumn customFieldColumn1 = new C1.Win.GanttView.CustomFieldColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn3 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn4 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn5 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn6 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn7 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn8 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn9 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn10 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn11 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn12 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn13 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.TaskPropertyColumn taskPropertyColumn14 = new C1.Win.GanttView.TaskPropertyColumn();
            C1.Win.GanttView.Task task1 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Resource resource1 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource2 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource3 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Resource resource4 = new C1.Win.GanttView.Resource();
            C1.Win.GanttView.Task task2 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task3 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.ResourceRef resourceRef1 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef2 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task4 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor1 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef3 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task5 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task6 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor2 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef4 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.ResourceRef resourceRef5 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task7 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor3 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef6 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task8 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Predecessor predecessor4 = new C1.Win.GanttView.Predecessor();
            C1.Win.GanttView.ResourceRef resourceRef7 = new C1.Win.GanttView.ResourceRef();
            C1.Win.GanttView.Task task9 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task10 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task11 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task12 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task13 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task14 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task15 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task16 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task17 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task18 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task19 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task20 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task21 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task22 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task23 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task24 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task25 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task26 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task27 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task28 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task29 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task30 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task31 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task32 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task33 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task34 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task35 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task36 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task37 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task38 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task39 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task40 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task41 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task42 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task43 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task44 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task45 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task46 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task47 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task48 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task49 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task50 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task51 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task52 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task53 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task54 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task55 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task56 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task57 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task58 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task59 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task60 = new C1.Win.GanttView.Task();
            C1.Win.GanttView.Task task61 = new C1.Win.GanttView.Task();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            gv = new C1.Win.GanttView.C1GanttView();
            ((System.ComponentModel.ISupportInitialize)gv).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gv.DataStorage.CalendarStorage).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gv.DataStorage.PropertyStorage).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gv.DataStorage.ResourceStorage).BeginInit();
            ((System.ComponentModel.ISupportInitialize)gv.DataStorage.TasksStorage).BeginInit();
            SuspendLayout();
            // 
            // gv
            // 
            gv.BackColor = System.Drawing.SystemColors.Window;
            barStyle1.BarColor = System.Drawing.Color.FromArgb(64, 135, 220);
            barStyle1.BarShape = C1.Win.GanttView.BarShape.ThickBar;
            barStyle1.BarType = C1.Win.GanttView.BarType.AutoTask;
            barStyle1.TopText1_ID = 287759160;
            barStyle3.BarColor = System.Drawing.Color.FromArgb(63, 63, 63);
            barStyle3.BarShape = C1.Win.GanttView.BarShape.MiddleBar;
            barStyle3.BarType = C1.Win.GanttView.BarType.Progress;
            gv.BarStyles.Add(barStyle1);
            gv.BarStyles.Add(barStyle2);
            gv.BarStyles.Add(barStyle3);
            gv.CellBorderColor = System.Drawing.Color.FromArgb(240, 240, 240);
            gv.ChartViewZoomFactor = 7F;
            taskPropertyColumn1.Caption = "Task Mode";
            taskPropertyColumn1.ID = 1680832599;
            taskPropertyColumn1.Property = C1.Win.GanttView.TaskProperty.Mode;
            taskPropertyColumn1.Visible = false;
            taskPropertyColumn1.Width = 61;
            taskPropertyColumn2.Caption = "Task Name";
            taskPropertyColumn2.ID = 375059526;
            taskPropertyColumn2.Property = C1.Win.GanttView.TaskProperty.Name;
            taskPropertyColumn2.Width = 93;
            customFieldColumn1.Caption = "Actual Cost";
            customFieldColumn1.DataType = typeof(decimal);
            customFieldColumn1.Format = "$#0";
            customFieldColumn1.ID = 79583976;
            customFieldColumn1.Name = "ActualCost";
            customFieldColumn1.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            customFieldColumn1.Width = 65;
            taskPropertyColumn3.Caption = "Duration";
            taskPropertyColumn3.ID = 1572034233;
            taskPropertyColumn3.Property = C1.Win.GanttView.TaskProperty.Duration;
            taskPropertyColumn3.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            taskPropertyColumn3.Width = 34;
            taskPropertyColumn4.Caption = "Duration Units";
            taskPropertyColumn4.ID = 688893641;
            taskPropertyColumn4.Property = C1.Win.GanttView.TaskProperty.DurationUnits;
            taskPropertyColumn4.Width = 60;
            taskPropertyColumn5.Caption = "Start";
            taskPropertyColumn5.ID = 1056085932;
            taskPropertyColumn5.Property = C1.Win.GanttView.TaskProperty.Start;
            taskPropertyColumn5.Visible = false;
            taskPropertyColumn6.Caption = "Finish";
            taskPropertyColumn6.ID = 536482953;
            taskPropertyColumn6.Property = C1.Win.GanttView.TaskProperty.Finish;
            taskPropertyColumn6.Visible = false;
            taskPropertyColumn7.Caption = "% Complete";
            taskPropertyColumn7.ID = 241887850;
            taskPropertyColumn7.Property = C1.Win.GanttView.TaskProperty.PercentComplete;
            taskPropertyColumn7.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            taskPropertyColumn7.Visible = false;
            taskPropertyColumn8.Caption = "Constraint Type";
            taskPropertyColumn8.ID = 1492723839;
            taskPropertyColumn8.Property = C1.Win.GanttView.TaskProperty.ConstraintType;
            taskPropertyColumn8.Visible = false;
            taskPropertyColumn9.Caption = "Constraint Date";
            taskPropertyColumn9.ID = 497084593;
            taskPropertyColumn9.Property = C1.Win.GanttView.TaskProperty.ConstraintDate;
            taskPropertyColumn9.Visible = false;
            taskPropertyColumn10.Caption = "Predecessors";
            taskPropertyColumn10.ID = 1887751057;
            taskPropertyColumn10.Property = C1.Win.GanttView.TaskProperty.Predecessors;
            taskPropertyColumn10.Visible = false;
            taskPropertyColumn11.Caption = "Deadline";
            taskPropertyColumn11.ID = 1454974103;
            taskPropertyColumn11.Property = C1.Win.GanttView.TaskProperty.Deadline;
            taskPropertyColumn11.Visible = false;
            taskPropertyColumn12.Caption = "Calendar";
            taskPropertyColumn12.ID = 365231808;
            taskPropertyColumn12.Property = C1.Win.GanttView.TaskProperty.Calendar;
            taskPropertyColumn12.Visible = false;
            taskPropertyColumn13.Caption = "Resource Names";
            taskPropertyColumn13.ID = 287759160;
            taskPropertyColumn13.Property = C1.Win.GanttView.TaskProperty.ResourceNames;
            taskPropertyColumn13.Visible = false;
            taskPropertyColumn14.Caption = "Notes";
            taskPropertyColumn14.ID = 1372220778;
            taskPropertyColumn14.Property = C1.Win.GanttView.TaskProperty.Notes;
            taskPropertyColumn14.Visible = false;
            gv.Columns.Add(taskPropertyColumn1);
            gv.Columns.Add(taskPropertyColumn2);
            gv.Columns.Add(customFieldColumn1);
            gv.Columns.Add(taskPropertyColumn3);
            gv.Columns.Add(taskPropertyColumn4);
            gv.Columns.Add(taskPropertyColumn5);
            gv.Columns.Add(taskPropertyColumn6);
            gv.Columns.Add(taskPropertyColumn7);
            gv.Columns.Add(taskPropertyColumn8);
            gv.Columns.Add(taskPropertyColumn9);
            gv.Columns.Add(taskPropertyColumn10);
            gv.Columns.Add(taskPropertyColumn11);
            gv.Columns.Add(taskPropertyColumn12);
            gv.Columns.Add(taskPropertyColumn13);
            gv.Columns.Add(taskPropertyColumn14);
            // 
            // 
            // 
            gv.DefaultWorkingTimes.Interval_1.Empty = false;
            gv.DefaultWorkingTimes.Interval_1.From = new System.DateTime(1, 1, 1, 9, 0, 0, 0);
            gv.DefaultWorkingTimes.Interval_1.FromInMinutes = 540;
            gv.DefaultWorkingTimes.Interval_1.To = new System.DateTime(1, 1, 1, 13, 0, 0, 0);
            gv.DefaultWorkingTimes.Interval_1.ToInMinutes = 780;
            gv.DefaultWorkingTimes.Interval_2.Empty = false;
            gv.DefaultWorkingTimes.Interval_2.From = new System.DateTime(1, 1, 1, 14, 0, 0, 0);
            gv.DefaultWorkingTimes.Interval_2.FromInMinutes = 840;
            gv.DefaultWorkingTimes.Interval_2.To = new System.DateTime(1, 1, 1, 18, 0, 0, 0);
            gv.DefaultWorkingTimes.Interval_2.ToInMinutes = 1080;
            gv.DefaultWorkingTimes.Interval_3.FromInMinutes = 0;
            gv.DefaultWorkingTimes.Interval_3.ToInMinutes = 1440;
            gv.DefaultWorkingTimes.Interval_4.FromInMinutes = 0;
            gv.DefaultWorkingTimes.Interval_4.ToInMinutes = 1440;
            gv.DefaultWorkingTimes.Interval_5.FromInMinutes = 0;
            gv.DefaultWorkingTimes.Interval_5.ToInMinutes = 1440;
            gv.Dock = System.Windows.Forms.DockStyle.Fill;
            gv.FixedBackColor = System.Drawing.Color.FromArgb(223, 227, 232);
            gv.FixedCellBorderColor = System.Drawing.Color.FromArgb(177, 181, 186);
            gv.FixedForeColor = System.Drawing.Color.Black;
            gv.GridWidth = 286;
            gv.GroupColumn = null;
            gv.HighlightBackColor = System.Drawing.Color.FromArgb(183, 219, 255);
            gv.HighlightForeColor = System.Drawing.Color.Black;
            gv.Location = new System.Drawing.Point(0, 0);
            gv.Margin = new System.Windows.Forms.Padding(4, 3, 4, 3);
            gv.Name = "gv";
            task1.ID = 1336949333;
            task1.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task1.Name = "Project Summary Task";
            task1.NextID = 0;
            gv.ProjectSummary = task1;
            resource1.Cost = new decimal(new int[] { 20000, 0, 0, 131072 });
            resource1.ID = 457479171;
            resource1.Name = "Adam Miller";
            resource1.NextID = 0;
            resource2.Cost = new decimal(new int[] { 50000, 0, 0, 131072 });
            resource2.ID = 574928631;
            resource2.Name = "Ruth Radelet";
            resource2.NextID = 0;
            resource3.Cost = new decimal(new int[] { 25000, 0, 0, 131072 });
            resource3.ID = 1258408175;
            resource3.Name = "Johnny Jewel";
            resource3.NextID = 0;
            resource4.Cost = new decimal(new int[] { 40000, 0, 0, 131072 });
            resource4.ID = 187715318;
            resource4.Name = "Nat Walker";
            resource4.NextID = 0;
            gv.Resources.AddRange(new C1.Win.GanttView.Resource[] { resource1, resource2, resource3, resource4 });
            gv.Size = new System.Drawing.Size(649, 350);
            gv.SplitterColor = System.Drawing.Color.FromArgb(177, 181, 186);
            gv.StartDate = new System.DateTime(2015, 4, 1, 0, 0, 0, 0);
            gv.TabIndex = 0;
            task2.ID = 1428331781;
            task2.NextID = 656460240;
            task3.ConstraintDate = new System.DateTime(2012, 6, 22, 0, 0, 0, 0);
            task3.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task3.Duration = 3D;
            task3.ID = 656460240;
            task3.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task3.Name = "Pursue a hare";
            task3.NextID = 132267904;
            task3.OutlineParentID = 1336949333;
            resourceRef1.Amount = 1D;
            resourceRef1.ResourceID = 457479171;
            resourceRef2.ResourceID = 1258408175;
            task3.ResourceRefs.Add(resourceRef1);
            task3.ResourceRefs.Add(resourceRef2);
            task4.ConstraintDate = new System.DateTime(2012, 6, 26, 0, 0, 0, 0);
            task4.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task4.Duration = 12D;
            task4.DurationUnits = C1.Win.GanttView.DurationUnits.Minutes;
            task4.ID = 132267904;
            task4.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task4.Name = "Hit the hare";
            task4.NextID = 704109188;
            task4.OutlineParentID = 1336949333;
            predecessor1.PredecessorTaskID = 656460240;
            task4.Predecessors.Add(predecessor1);
            resourceRef3.Amount = 1D;
            resourceRef3.ResourceID = 187715318;
            task4.ResourceRefs.Add(resourceRef3);
            task5.ID = 704109188;
            task5.NextID = 1639616200;
            task6.ConstraintDate = new System.DateTime(2012, 6, 28, 0, 0, 0, 0);
            task6.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task6.Duration = 2D;
            task6.ID = 1639616200;
            task6.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task6.Name = "Skin that hare";
            task6.NextID = 1784420689;
            task6.OutlineParentID = 1336949333;
            predecessor2.PredecessorTaskID = 132267904;
            task6.Predecessors.Add(predecessor2);
            resourceRef4.Amount = 1D;
            resourceRef4.ResourceID = 187715318;
            resourceRef5.Amount = 1D;
            resourceRef5.ResourceID = 1258408175;
            task6.ResourceRefs.Add(resourceRef4);
            task6.ResourceRefs.Add(resourceRef5);
            task7.ConstraintDate = new System.DateTime(2012, 6, 29, 0, 0, 0, 0);
            task7.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task7.Duration = 3D;
            task7.ID = 1784420689;
            task7.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task7.Name = "Cook the hare";
            task7.NextID = 1296539678;
            task7.OutlineParentID = 1336949333;
            predecessor3.PredecessorTaskID = 1639616200;
            task7.Predecessors.Add(predecessor3);
            resourceRef6.Amount = 1D;
            resourceRef6.ResourceID = 574928631;
            task7.ResourceRefs.Add(resourceRef6);
            task8.ConstraintDate = new System.DateTime(2012, 6, 30, 0, 0, 0, 0);
            task8.ConstraintType = C1.Win.GanttView.ConstraintType.StartNoEarlierThan;
            task8.Duration = 1D;
            task8.ID = 1296539678;
            task8.Mode = C1.Win.GanttView.TaskMode.Automatic;
            task8.Name = "Eat the hare";
            task8.NextID = 1444841716;
            task8.OutlineParentID = 1336949333;
            predecessor4.PredecessorTaskID = 1784420689;
            task8.Predecessors.Add(predecessor4);
            resourceRef7.Amount = 1D;
            resourceRef7.ResourceID = 457479171;
            task8.ResourceRefs.Add(resourceRef7);
            task9.ID = 1444841716;
            task9.NextID = 1292198183;
            task10.ID = 1292198183;
            task10.NextID = 194872062;
            task11.ID = 194872062;
            task11.NextID = 1084382609;
            task12.ID = 1084382609;
            task12.NextID = 185961251;
            task13.ID = 185961251;
            task13.NextID = 393559994;
            task14.ID = 393559994;
            task14.NextID = 92150478;
            task15.ID = 92150478;
            task15.NextID = 20990948;
            task16.ID = 20990948;
            task16.NextID = 1623847046;
            task17.ID = 1623847046;
            task17.NextID = 1884750761;
            task18.ID = 1884750761;
            task18.NextID = 1112867871;
            task19.ID = 1112867871;
            task19.NextID = 43920728;
            task20.ID = 43920728;
            task20.NextID = 149186310;
            task21.ID = 149186310;
            task21.NextID = 1021263795;
            task22.ID = 1021263795;
            task22.NextID = 242707790;
            task23.ID = 242707790;
            task23.NextID = 1748838715;
            task24.ID = 1748838715;
            task24.NextID = 506851181;
            task25.ID = 506851181;
            task25.NextID = 791484787;
            task26.ID = 791484787;
            task26.NextID = 572119585;
            task27.ID = 572119585;
            task27.NextID = 2026106759;
            task28.ID = 2026106759;
            task28.NextID = 39792468;
            task29.ID = 39792468;
            task29.NextID = 86367301;
            task30.ID = 86367301;
            task30.NextID = 1099725135;
            task31.ID = 1099725135;
            task31.NextID = 454310966;
            task32.ID = 454310966;
            task32.NextID = 604586163;
            task33.ID = 604586163;
            task33.NextID = 1249515592;
            task34.ID = 1249515592;
            task34.NextID = 1587165775;
            task35.ID = 1587165775;
            task35.NextID = 82220786;
            task36.ID = 82220786;
            task36.NextID = 1611700704;
            task37.ID = 1611700704;
            task37.NextID = 833779805;
            task38.ID = 833779805;
            task38.NextID = 77200479;
            task39.ID = 77200479;
            task39.NextID = 1549556208;
            task40.ID = 1549556208;
            task40.NextID = 1589311134;
            task41.ID = 1589311134;
            task41.NextID = 825958818;
            task42.ID = 825958818;
            task42.NextID = 235990884;
            task43.ID = 235990884;
            task43.NextID = 1230344991;
            task44.ID = 1230344991;
            task44.NextID = 1377162172;
            task45.ID = 1377162172;
            task45.NextID = 1751994680;
            task46.ID = 1751994680;
            task46.NextID = 870124682;
            task47.ID = 870124682;
            task47.NextID = 142922960;
            task48.ID = 142922960;
            task48.NextID = 149737373;
            task49.ID = 149737373;
            task49.NextID = 1471732892;
            task50.ID = 1471732892;
            task50.NextID = 1020721195;
            task51.ID = 1020721195;
            task51.NextID = 3000297;
            task52.ID = 3000297;
            task52.NextID = 342106233;
            task53.ID = 342106233;
            task53.NextID = 321311081;
            task54.ID = 321311081;
            task54.NextID = 138572851;
            task55.ID = 138572851;
            task55.NextID = 350956984;
            task56.ID = 350956984;
            task56.NextID = 413752451;
            task57.ID = 413752451;
            task57.NextID = 530912837;
            task58.ID = 530912837;
            task58.NextID = 921480601;
            task59.ID = 921480601;
            task59.NextID = 848131414;
            task60.ID = 848131414;
            task60.NextID = 1212301105;
            task61.ID = 1212301105;
            task61.NextID = -1;
            gv.Tasks.AddRange(new C1.Win.GanttView.Task[] { task2, task3, task4, task5, task6, task7, task8, task9, task10, task11, task12, task13, task14, task15, task16, task17, task18, task19, task20, task21, task22, task23, task24, task25, task26, task27, task28, task29, task30, task31, task32, task33, task34, task35, task36, task37, task38, task39, task40, task41, task42, task43, task44, task45, task46, task47, task48, task49, task50, task51, task52, task53, task54, task55, task56, task57, task58, task59, task60, task61 });
            gv.Timescale.BottomTier.Align = C1.Win.GanttView.ScaleLabelAlignment.Center;
            gv.Timescale.BottomTier.Format = "w";
            gv.Timescale.BottomTier.Visible = true;
            gv.Timescale.MiddleTier.Format = "nnnn d";
            gv.Timescale.MiddleTier.Units = C1.Win.GanttView.TimescaleUnits.Weeks;
            gv.Timescale.MiddleTier.Visible = true;
            gv.ToolbarBackColor = System.Drawing.Color.FromArgb(223, 227, 232);
            gv.VisualStyle = C1.Win.GanttView.VisualStyle.Office2010Silver;
            // 
            // Form1
            // 
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            ClientSize = new System.Drawing.Size(649, 350);
            Controls.Add(gv);
            Font = new System.Drawing.Font("Segoe UI", 9F);
            Icon = (System.Drawing.Icon)resources.GetObject("$this.Icon");
            Name = "Form1";
            Text = "Custom Column Demo";
            Load += Form1_Load;
            ((System.ComponentModel.ISupportInitialize)gv.DataStorage.CalendarStorage).EndInit();
            ((System.ComponentModel.ISupportInitialize)gv.DataStorage.PropertyStorage).EndInit();
            ((System.ComponentModel.ISupportInitialize)gv.DataStorage.ResourceStorage).EndInit();
            ((System.ComponentModel.ISupportInitialize)gv.DataStorage.TasksStorage).EndInit();
            ((System.ComponentModel.ISupportInitialize)gv).EndInit();
            ResumeLayout(false);

        }

        #endregion

        private C1.Win.GanttView.C1GanttView gv;
    }
}

